### ISSUE TITLE
`_⊎_` from Connectives.agda no longer compiles in 2.6.4

### ISSUE THREAD

**Issue by JacquesCarette** [plfa/plfa.github.io#1023]
The problem is that the definition confuses parameters and indicies. The "correct" definition would be
```agda
data _⊎_ (A : Set) (B : Set) : Set where

  inj₁ : 
      A
      -----
    → A ⊎ B

  inj₂ :
      B
      -----
    → A ⊎ B
```
(which is what is essentially in the standard library)

**Comment by wadler** [comment]
I'm confused. What is in the book currently is:
```
data _⊎_ (A B : Set) : Set where

  inj₁ :
      A
      -----
    → A ⊎ B

  inj₂ :
      B
      -----
    → A ⊎ B
```
(a) That compiles fine under 2.6.4.1.
(b) I don't see how it differs from your suggested correction.

**Comment by JacquesCarette** [comment]
My error! I apparently had some older versions of the files around which did have that "bug". I see that this is indeed fixed now.

Looks like I'm going to have to rebuild all my live-coding, full-of-holes Agda files from scratch from current PLFA. Glad that I caught it now instead of during a lecture...

**Comment by wadler** [comment]
OK. Thanks for checking.
