### ISSUE TITLE
Issues with imports in the book?

### ISSUE THREAD

**Issue by lidorcg** [plfa/plfa.github.io#1043]
Sorry if it sounds unnecessarily generelized but I'm 2/2 so I though to ask:

When I try to load `Naturals` & `Induction` as is, I'm facing (very) small issues with imports such as:
```
Not in scope:
  ≡⟨⟩
  at ~/Workspace/plfa/src/plfa/part1/Induction.lagda.md:99,3-6
    (did you mean 'Eq.≡-Reasoning._≡⟨⟩_'?)
when scope checking ≡⟨⟩
```

The issues are quite easy to fix, but if everyone experiencing this issue then I will PR, if not then why am I?

**Comment by wadler** [comment]
These imports changed with the recent upgrade to agda-stdlib v2.1. If you have the correct version of the library and the most recent version of PLFA, you should find the problem fixed.
