### ISSUE TITLE
Definition Formatting of Addition Different to Multiplication

### ISSUE THREAD

**Issue by leifmetcalf** [plfa/plfa.github.io#105]
This is the book's addition definition:
```agda
_+_ : ℕ → ℕ → ℕ
zero + n = n
suc m + n = suc (m + n)
```
This is the book's multiplication definition:
```agda
_*_ : ℕ → ℕ → ℕ
zero * n     =  zero
(suc m) * n  =  n + (m * n)
```
These things are different:
- `suc m` is surrounded in brackets in the multiplication definition, and isn't in the addition definition
- `=` is surrounded by two spaces on each side in the multiplication definition, and by one space in the addition definition
- The `=` symbols are aligned in the multiplication definition, and are not in the addition definition

I do not know much about Agda so there may be a functional reason for these differences. I have changed the formatting of the multiplication definition to be the same as the formatting of the addition definition and have not noticed any functional differences.

**Comment by wenkokke** [comment]
@leifmetcalf There aren't any functional differences, these are simply some wrinkles in formatting that we're still trying to iron out. Thanks for pointing this one out!
