### ISSUE TITLE
mention absurd pattern before exercise `≤-iff-<` in chapter Relation

### ISSUE THREAD

**Issue by seven-two-eight** [plfa/plfa.github.io#119]
I'm only new to Agda and I'm trying to pick up Agda through PLFA. Let me know if what I'm saying makes sense.

By the point we reach [exercise `≤-iff-<`](https://github.com/plfa/plfa.github.io/blob/30e7928c8fcca09deab4ebfc3df31cbebf0e1315/src/plfa/Relations.lagda#L562), there is no mentioning of absurd pattern, which seems to be necessary here.

I only learned about this after asking for help on [reddit](https://www.reddit.com/r/agda/comments/a3ic6d/help_prove_a_strict_inequality_property/). I don't think I could have figured this out by myself.

Is it true we need absurd pattern here? If so, shouldn't absurd pattern be mentioned prior to this exercise?

**Comment by wenkokke** [comment]
You don't need the absurd pattern to complete this exercise. Try proving it by induction on the proof that `suc m ≤ n`, instead of by induction on `m` and `n`.
