### ISSUE TITLE
Using the PLFA Agda standard library

### ISSUE THREAD

**Issue by mdimjasevic** [plfa/plfa.github.io#124]
I'm a Debian GNU/Linux user and I installed Debian packages `agda` at version 2.5.1.1 and `agda-stdlib` at version 0.12, which are for the language and its standard library, respectively. With it I get an `Invalid name: _` error with files like `Naturals.lagda` and `Induction.lagda` from the PLFA book. Therefore, I thought I'd use your [custom version](https://github.com/plfa/agda-stdlib) of the standard library in an attempt to get around this. I added your fork of the standard library to `defaults` and `libraries` in my `AGDA_DIR` directory and removed any pointers to the system-wide installation of the library, which resides in `/usr/share/agda-stdlib/`. However, with my solution to your assignment where I have this import:

```agda
import Relation.Binary.PropositionalEquality as Eq
```

I get the following error:

```
/home/marko/projects/learning-agda/plfa-exercises/plfa/InductionExercises.lagda:4,8-51
Ambiguous module name. The module name
Relation.Binary.PropositionalEquality could refer to any of the
following files:
  /home/marko/projects/agda/plfa-agda-stdlib/src/Relation/Binary/PropositionalEquality.agda
  /usr/share/agda-stdlib/Relation/Binary/PropositionalEquality.agda
when scope checking the declaration
  import Relation.Binary.PropositionalEquality as Eq
```

How do I get around this? Can I somehow hide the system-wide installation of the standard library at `/usr/share/agda-stdlib/`?

**Comment by wenkokke** [comment]
@mdimjasevic We don't actually have a custom version of the standard library – it's simply a tag, there's no code in there which isn't in the standard library. That said, your problem is indeed that you have two installations of the standard library. What exactly is going wrong, I have no idea. Maybe you need to recompile agda-mode? Maybe you have the include path to /usr/share/agda-stdlib/ setup as a parameter, the old way?

**Comment by mdimjasevic** [comment]
I got this working by removing the system-wide installations of Agda and the standard library and using manually installations of the two.
