### ISSUE TITLE
≤ᵇ→≤: Explanation of last clause of definition

### ISSUE THREAD

**Issue by whxvd** [plfa/plfa.github.io#139]
The definition:
```
≤ᵇ→≤ : ∀ (m n : ℕ) → T (m ≤ᵇ n) → m ≤ n
≤ᵇ→≤ zero    n       tt  =  z≤n
≤ᵇ→≤ (suc m) zero ()
≤ᵇ→≤ (suc m) (suc n) t = s≤s (≤ᵇ→≤ m n t)
```
The explanation for the last clause:
```
In the last clause, we have the `suc m ≤ suc n` recurses
to `m ≤ n` and we let `t` be the evidence of `T (m ≤ᵇ n)` if it exists.
We recursively invoke the function to get evidence that `m ≤ n`, which
`s≤s` converts to evidence that `suc m ≤ suc n`.
```
Depending on how you view it, the explanation is not correct. Because we let `t` be the evidence of `T (suc m ≤ᵇ suc n)`. And not of `T (m ≤ᵇ n)`.

However, by definition of `≤ᵇ` we have `suc m ≤ᵇ suc n` = `m ≤ᵇ n`. Because of this, evidence for `T (suc m ≤ᵇ suc n)` also is evidence for `T (m ≤ᵇ n)`. That is the ultimate reason we can just use t on the right hand side of the last clause.

Somehow Agda finds it out by itself. But I find it essential for understanding the code and/or trusting/following the reasoning that is going on.

**Comment by wadler** [comment]
Thank you for the suggestion. Fixed now. Next time, try suggesting your own improved wording in a pull request.
