### ISSUE TITLE
How am I supposed to work through this book?

### ISSUE THREAD

**Issue by mwhicks1** [plfa/plfa.github.io#143]
I'm sorry for the newbie question: How am I supposed to go through this material using agda?

I have no prior experience with agda, and I was hoping to start to get that experience using this book. I've read the README and read much of the HTML for the first lesson. I've installed agda and its standard library, and I think the emacs mode is loading properly.

I'm quite familiar with Software Foundations, for which you simply edit the .v files and work through them in proof general and Coq. For PLFA, there are a bunch of .lagda files --- how do I use Agda with these, to play around with them? Do I need to build the book? Is the server necessary? 

A little more help from the documentation, perhaps with pointers to the relevant parts of the agda documentation, would be welcome.

**Comment by mwhicks1** [comment]
OK, good. I have loaded Naturals.lagda and done C-c C-l to load the file. There are a couple of places where the instructions present an exercise. How am I supposed to edit the file to complete it, as I might in Software Foundations? Should I introduce a \begin{code} ... \end{code} and edit the ... to do it, and then re-load the file? I'm wondering how interaction in agda works with literate files.

**Comment by k4rtik** [comment]
I found those things confusing too. In my case, I ended up creating a separate file `scratch.agda` and imported required definitions to work on the exercises. One of the main reasons I wanted to do that was to avoid writing `\begin{code}` `\end{code}` blocks for each exercise but in turn, I sometimes need to do copy-paste definitions introduced in the chapters.

In Software Foundations, this is not necessary as the code is the default in a `.v` file, while in literate agda files, prose is default and code needs to be marked out specially in a block. I wonder if it might be a good idea to provide templates for each exercise, so it is clear for a beginner to figure out where to write the solutions.

**Comment by wenkokke** [comment]
@k4rtik This does sound like a good idea. If I remember correctly, in some cases we have `\begin{code}` `\end{code}` blocks with a postulate with the appropriate name in there, but this can't be done for exercises where writing down the type is part of the exercise. Do you feel it would still be beneficial to have empty `\begin{code}` `\end{code}` blocks for each exercise which requires code?

**Comment by k4rtik** [comment]
I was thinking something like this (from `Induction.lagda`):
```
#### Exercise `+-swap` (recommended) {#plus-swap} 

\begin{code}
-- Your code goes here
\end{code}
```

It probably makes sense to have it at least once in the first chapter to give an introduction to a beginner. I am lazy, so I would prefer having it after each exercise, but that's just me. :)

**Comment by wenkokke** [comment]
@wadler Opinions? I think this is a good idea.

**Comment by ywata** [comment]
I like the idea too for two reasons.
1. It's beginner friendly.
2. This reduces variation how to solve exercises and that may make a bit more  chance to automatic merge can work when text is added or modified.

My concern for this change is some  existing reader may encounter conflicts against latest source code after merge if she/he put their code block in different location on their .lagda file.

I almost mechanically added code block after #### Exercise line in the branch below:
https://github.com/ywata/plfa.github.io/tree/code-block
If you merge the changes, I'll send a PR from the location.

**Comment by wenkokke** [comment]
@ywata Could you open a pull request?
