### ISSUE TITLE
Using built-in equality

### ISSUE THREAD

**Issue by mdimjasevic** [plfa/plfa.github.io#156]
I've been reading the chapter on equality and I got to the point where a reader is instructed to add the following:

```agda
{-# BUILTIN EQUALITY _≡_ #-}
```

However, when I do that, I get the following error:

```
Set .a != Set
when checking that the expression _≡_ has type .A → .A → Set .a
```

This happens with Agda version 2.5.1.1 and Agda standard library version 0.12. I can't see why so any help would be appreciated.

**Comment by wenkokke** [comment]
Have you tried to do the same with the Agda versions we use – see the README or [Getting Started](https://plfa.github.io/GettingStarted/)?

**Comment by mdimjasevic** [comment]
You are right. This indeed works with Agda 2.5.4.2 and the standard library at version 0.17. I'll have to read about Agda versioning and when they break their interfaces.
