### ISSUE TITLE
Inability to use the PLFA library as it is

### ISSUE THREAD

**Issue by mdimjasevic** [plfa/plfa.github.io#178]
I'd like to be able to use the PLFA library (i.e., `.lagda` book files) as they are in solving exercises given in the book. However, the library files don't type-check. For example, I'm reading the chapter on connectives now and I'd like to solve the `⇔≃×` exercise. If in my file `ConnectivesExercises.agda` I try to add these imports:

```agda
open import plfa.Isomorphism using (_≃_; ≃-sym; ≃-trans; _≲_; extensionality)
open plfa.Isomorphism.≃-Reasoning
```

and I do `C-c C-l` in an Emacs buffer, I get the following:

```
/home/marko/projects/agda/plfa.github.io/src/plfa/Isomorphism.lagda:324,5-20
Multiple definitions of to. Previous definition at
/home/marko/projects/agda/plfa.github.io/src/plfa/Isomorphism.lagda:142,5-7
when scope checking the declaration
  field to : A → B
```

It would be great if the code sections in the book were reorganised so that the whole book passes Agda's type-checking. Then the book could be used as a library, including in solving exercises given in the book. I'd be happy to work on updating the book so that it can be used in such a way.

**Comment by wadler** [comment]
The book is already designed to be used as a library, and has been used in that way for exercises in my class. Have you followed the instructions in the first section of the "Getting Started" page? Do you have an up to date version of the standard library?

**Comment by wenkokke** [comment]
The problem is caused not by any required setup of PLFA as a library. It is caused by defining the name `to` twice in Isomorphism.

Once at line 142:

```agda
infix 0 _≃_
record _≃_ (A B : Set) : Set where
  field
    to   : A → B
    from : B → A
    from∘to : ∀ (x : A) → from (to x) ≡ x
    to∘from : ∀ (y : B) → to (from y) ≡ y
open _≃_
```

Once at line 324:

```agda
infix 0 _≲_
record _≲_ (A B : Set) : Set where
  field
    to      : A → B
    from    : B → A
    from∘to : ∀ (x : A) → from (to x) ≡ x
open _≲_
```

This is a problem – and worse, one that only becomes apparent when you try to _use_ `to` – which we'll have to address, probably by removing the `open` statements.

**Comment by wenkokke** [comment]
The problem is caused not by any required setup of PLFA as a library. It is caused by defining the name `to` twice in Isomorphism. Once at line 142:

```agda
infix 0 _≃_
record _≃_ (A B : Set) : Set where
  field
    to   : A → B
    from : B → A
    from∘to : ∀ (x : A) → from (to x) ≡ x
    to∘from : ∀ (y : B) → to (from y) ≡ y
open _≃_
```

Once at line 324:

```agda
infix 0 _≲_
record _≲_ (A B : Set) : Set where
  field
    to      : A → B
    from    : B → A
    from∘to : ∀ (x : A) → from (to x) ≡ x
open _≲_
```

This is a problem – and worse, one that only becomes apparent when you try to _use_ `to` – which we'll have to address, probably by removing the `open` statements.

**Comment by mdimjasevic** [comment]
Philip, I can confirm what Wen said: indeed, it is not an issue caused by my setup; rather, it is a bug in the library because the name `to` is defined twice in the same Agda module. You can try it yourself and you will see this is really the case. Let me know if you're OK with it and I can start reorganising the code chapter by chapter, ensuring that I don't introduce new compilation/type-checking problems as I go.

**Comment by wenkokke** [comment]
This is a rather strange error, because we're able to use `to` unambiguously _within_ the module, but not outside of it. If anyone has any ideas of what behaviour in Agda is causing this, hints would be welcome.

**Comment by mdimjasevic** [comment]
I'm not seeing this happening any more. Not sure what happened in the meantime, but maybe I upgraded my Agda version. I'll close it for now and if I run into this issue again, I'll reopen it.
