### ISSUE TITLE
Connectives: exercises for the empty type

### ISSUE THREAD

**Issue by mdimjasevic** [plfa/plfa.github.io#187]
In the chapter on connectives, there is a section titled _False is empty_. At the end of the section, there are two exercises named and described as:

1) `⊥-identityˡ` - Show zero is the left identity of addition.
2) `⊥-identityʳ` - Show zero is the right identity of addition.

Names can be misleading, but I just wanted to check - shouldn't the exercises be about showing that empty is identity of sums up to isomorphism? If so, I'd be happy to make a pull request that addresses this.

**Comment by wadler** [comment]
Good point. Please make your suggested clarification.
