### ISSUE TITLE
Bin-embedding stretch exercise in Isomorphism chapter suggests inaccurate conclusion

### ISSUE THREAD

**Issue by dkrejsa** [plfa/plfa.github.io#191]

**Comment by dkrejsa** [comment]
The Bin-embedding stretch exercise in the Isomorphism chapter suggests that there is no isomorphism
ℕ ≃ Bin.  But there is; just not one that preserves the desired arithmetic correspondence defined in the previous Bin-related exercises.  Here's an example isomorphism:

    \begin{code}
    open import Data.Nat.Properties using (+-suc)

    ℕ≃Bin : ℕ ≃ Bin
    ℕ≃Bin = record { to = toB ; from = fromB ; from∘to = fromB∘toB ; to∘from = toB∘fromB }
      where
        pred : ℕ -> ℕ
        pred zero = zero
        pred (suc n) = n

        bsuc : Bin -> Bin
        bsuc nil = x0 nil -- 2
        bsuc (x0 x) = x1 x
        bsuc (x1 x) = x0 (bsuc x)

        toB' : ℕ -> Bin
        toB' zero = nil   -- arbitrary, unused
        toB' (suc zero) = nil  -- i.e., binary 1
        toB' (suc (suc n)) = bsuc (toB' (suc n))

        fromB' : Bin -> ℕ
        fromB' nil = 1
        fromB' (x0 x) = fromB' x + fromB' x
        fromB' (x1 x) = suc (fromB' x + fromB' x)

        fromB'∘bsuc : (x : Bin) -> fromB' (bsuc x) ≡ suc (fromB' x)
        fromB'∘bsuc nil = refl
        fromB'∘bsuc (x0 x) = refl
        fromB'∘bsuc (x1 x) rewrite fromB'∘bsuc x | +-suc (fromB' x) (fromB' x) = refl

        toB : ℕ -> Bin
        toB n = toB' (suc n)

        fromB : Bin -> ℕ
        fromB x = pred (fromB' x)

        fromB'∘toB' : ∀ n -> fromB' (toB' (suc n)) ≡ suc n
        fromB'∘toB' zero = refl
        fromB'∘toB' (suc n) rewrite fromB'∘bsuc (toB' (suc n)) = cong suc (fromB'∘toB' n)

        toB'2sn : ∀ n -> toB' (suc n + suc n) ≡ x0 (toB' (suc n))
        toB'2sn zero = refl
        toB'2sn (suc n) rewrite +-suc n (suc n) | toB'2sn n = refl

        suc∘pred∘fromB' : (x : Bin) -> fromB' x ≡ suc (pred (fromB' x))
        suc∘pred∘fromB' nil = refl
        suc∘pred∘fromB' (x0 x) rewrite suc∘pred∘fromB' x = refl
        suc∘pred∘fromB' (x1 x) = refl

        toB'∘fromB' : (x : Bin) -> toB' (fromB' x) ≡ x
        toB'∘fromB' nil = refl
        toB'∘fromB' (x0 x) rewrite suc∘pred∘fromB' x |
                                   toB'2sn (pred (fromB' x)) |
                                   sym (suc∘pred∘fromB' x) |
                                   toB'∘fromB' x = refl
        toB'∘fromB' (x1 x) rewrite suc∘pred∘fromB' x |
                                   toB'2sn (pred (fromB' x)) |
                                   sym (suc∘pred∘fromB' x) |
                                   toB'∘fromB' x = refl

        fromB∘toB : ∀ n -> fromB (toB n) ≡ n
        fromB∘toB n = cong pred (fromB'∘toB' n)

        toB∘fromB : ∀ x -> toB (fromB x) ≡ x
        toB∘fromB x rewrite sym (suc∘pred∘fromB' x) = toB'∘fromB' x
    \end{code}

**Comment by wadler** [comment]
Good point! I've rewritten the exercise to clarify.

That was a lot of work on your part! I've saved it in my answers repository (which is not public in order to discourage simply copying answers), and it may form the basis for a future exercise. Please confirm if you are happy with that.

**Comment by dkrejsa** [comment]
That's fine, thanks!

**Comment by dkrejsa** [comment]
BTW, I just got around to the Bin-isomorphism exercise in the Quantifiers chapter.
I interpreted the exercise in an abstract sense, i.e. I wanted to prove it for _any_ terms to / from / Can
with the specified properties.  I couldn't quite do it; I had to make one additional assumption,

    propCan : (x : Bin) (r s : Can x) -> r ≡ s

(which basically says that (Can x) is a proposition in the HoTT sense), and then I could prove that

    bincanex : (toBin : ℕ -> Bin) (fromBin : Bin -> ℕ) (Can : Bin -> Set)
               (from-to : (n : ℕ) -> (fromBin (toBin n) ≡ n))
               (to-fromCan : (x : Bin) -> Can x -> toBin (fromBin x) ≡ x)
               (toCan : (n : ℕ) -> Can (toBin n))
               (propCan : (x : Bin) (r s : Can x) -> r ≡ s)
               -> ℕ ≃ ∃[ x ] (Can x)

although it required a bit of knowledge about equalities in dependent sums.
Proving propCan for the particular concrete Can defined in the earlier exercises wasn't too hard.
