### ISSUE TITLE
More: Code block for exercise in More.lagda

### ISSUE THREAD

**Issue by ywata** [plfa/plfa.github.io#210]
To apply proposed change in #143, I put code blocks with simple script before reading the contents (#181).
Now I'm reading More.lagda and I'm wondering adding code block at the end of More.lagda might not be what is originally intended or not.
I'd like to know how we solve the exercise in More.lagda.
There are at least two possibilities:
(a).  Add code, ex. code for sums,  in existing definition. 
(b).  Copy all the existing code to the end of the section after 'Your code goes here'. And start adding code for exercises.

(a) is easy and (b) introduces naming issue.
If (a) is what originally intended, I'd like to propose to remove the code block I previously added.
If (b) and using inner module is intended, I'd like to propose to include
`  module exercise where` line in the code block.

**Comment by wenkokke** [comment]
@ywata Yeah, that code block should be removed, as the intention is to edit the entirety of More.lagda.

**Comment by wadler** [comment]
Yes, that's right. Thanks, guys!
