### ISSUE TITLE
make build failed

### ISSUE THREAD

**Issue by ywata** [plfa/plfa.github.io#213]
During my trial, I encountered two issues. I resolved one  but the other not.

- I had to include `standard-library` in `~/.agda/defaults`
- Currently, I have the following error

```
agda2html --verbose --link-to-local-agda-names --use-jekyll=out/ --link-to-agda-stdlib -i src/tmp/Quantitative.lagda -o out/tmp/Quantitative.md 2>&1 \
                | sed '/^Generating.*/d; /^Warning\: HTML.*/d; /^reached from the.*/d; /^\s*$/d'
/Users/test/work/plfa.github.io/src/tmp/Quantitative.lagda:57,8-25
The name of the top level module does not match the file name. The
module plfa.Quantitative should be defined in one of the following
files:
  /private/var/folders/k2/1jkk2gts1xn0scns9ym3r6m00000gn/T/agda2html10320/plfa/Quantitative.agda
  /private/var/folders/k2/1jkk2gts1xn0scns9ym3r6m00000gn/T/agda2html10320/plfa/Quantitative.lagda
  /Users/test/lang/agda/agda-stdlib/src/plfa/Quantitative.agda
  /Users/test/lang/agda/agda-stdlib/src/plfa/Quantitative.lagda
  /Users/test/work/plfa.github.io/src/tmp/plfa/Quantitative.agda
  /Users/test/work/plfa.github.io/src/tmp/plfa/Quantitative.lagda
  /Users/test/lang/agda/agda-2.5.4.2/.stack-work/install/x86_64-osx/lts-12.16/8.4.4/share/x86_64-osx-ghc-8.4.4/Agda-2.5.4.2/lib/prim/plfa/Quantitative.agda
  /Users/test/lang/agda/agda-2.5.4.2/.stack-work/install/x86_64-osx/lts-12.16/8.4.4/share/x86_64-osx-ghc-8.4.4/Agda-2.5.4.2/lib/prim/plfa/Quantitative.lagda
agda --allow-unsolved-metas --html '--html-dir=/private/var/folders/k2/1jkk2gts1xn0scns9ym3r6m00000gn/T/agda2html10320' '--include-path=/Users/test/work/plfa.github.io/src/tmp' /Users/test/work/plfa.github.io/src/tmp/Quantitative.lagda
```

**Comment by wenkokke** [comment]
Ah! I'm pretty sure I know what's going on – `agda2html` isn't used to dealing with parameterised modules!

**Comment by ywata** [comment]
@wenkokke 
You're welcome.

**Comment by wenkokke** [comment]
Actually, @ywata, could you let me know what your `agda2html` version is? I think I fixed this bug quite a while ago, but you might still have an older version. The latest version is `2.3.0`.

**Comment by ywata** [comment]
@wenkokke 
% agda2html  --version
agda2html 0.2.3.0
Is this latest?

**Comment by wenkokke** [comment]
Yup, which isn't great news, 'cuz the build is working on Travis and on my machine.

**Comment by ywata** [comment]
I installed icu4c with brew. I've got this error.
[log.txt](https://github.com/plfa/plfa.github.io/files/2941485/log.txt)
I got the error when I first built agda2html and resolved, which I do not remember how now.
I may miss something.

**Comment by ywata** [comment]
@wenkokke 
I finally succeeded in running make build on my Mac.
I need to build agda2html with lts-13.13 as resolver. And it seems to resolve everything.
I could run make build and make serve as expected. Now, I can read the book on my PC without network access to internet.

Thanks.
