### ISSUE TITLE
Connectives: Sum and product inconsistent fixity (?)

### ISSUE THREAD

**Issue by googleson78** [plfa/plfa.github.io#223]
The product type is declared as associating to the right
```
infixr 2 _×_
```
whereas the sum type is declared as *not* associating without brackets.
```
infix 1 _⊎_
```

Is this done on purpose?

**Comment by wadler** [comment]
Good catch. They should be consistent, I suggest both right associative. Googleson, would you make this change so it can be accepted as a pull request? Many thanks.
