### ISSUE TITLE
Lists: meaning of the verb append

### ISSUE THREAD

**Issue by mdimjasevic** [plfa/plfa.github.io#227]
There are multiple definitions of the verb append and according to the [Wiktionary](https://en.wiktionary.org/wiki/append), in computing it means:

> (computing) To write more data to the end of a pre-existing file, string, or other non-constant data type.

With that interpretation of the verb append, wouldn't it be wrong to say in an elaboration of the `append` function that is defined as:

```agda
_++_ : ∀ {A : Set} → List A → List A → List A
[]       ++ ys  =  ys
(x ∷ xs) ++ ys  =  x ∷ (xs ++ ys)
```

that "the empty list appended to another list yields the other list"? Shouldn't it be the other way around because the list `ys` is appended here? The same goes for the elaboration of the second equation.

Maybe I'm just being picky here.

**Comment by wenkokke** [comment]
No, this is actually a fair point.
