### ISSUE TITLE
Would it be possible to clarify what is the minimum version of Agda needed to run the plfa examples?

### ISSUE THREAD

**Issue by hugomg** [plfa/plfa.github.io#245]
A colleague of mine is still using Ubuntu 16.04, and the version of Agda available from its official repositories (2.4.2) seems to be too old to run the examples from this book. For example, when I try to load Naturals.lagda it shows an `Invalid name: _` error.

Does anyone happen to know what is the minimum version of Agda needed to go through this book? If so, perhaps it would be helpful to add this information to the README / Getting Started page.

**Comment by wadler** [comment]
It's hard to keep track of the minimum version that works. Instead, we put up badges (on the Getting Started page) to tell you versions of the compiler and libraries that we know will work. You can usually install such a version without too much hassle by loading and compiling sources, although that may take a while. (If someone is motivated to work out additional compiler/library combinations that work with the book, please tell us what they are via pull requests to the Getting Started page.)

**Comment by hugomg** [comment]
Thanks. I have to confess that I totally did not notice the badges, due to "banner blindness".
