### ISSUE TITLE
Lambda: Possibly Incorrect Quiz Question two · sucᶜ · `zero

### ISSUE THREAD

**Issue by mdimjasevic** [plfa/plfa.github.io#252]
In the chapter on Lambda calculus in the section on reduction, there is this quiz question:

"What does the following term step to? (Where `two` and `sucᶜ` are as defined above.)

```
    two · sucᶜ · `zero  —→  ???

    sucᶜ · (sucᶜ · `zero)
    (ƛ "z" ⇒ sucᶜ · (sucᶜ · ` "z")) · `zero
    `zero
```
"

Should the term have been ```twoᶜ · sucᶜ · `zero``` instead, where the term ```twoᶜ``` is used instead of ```two```? If so, I can make a patch that updates this.

**Comment by wadler** [comment]
Yes! Good catch. With `two` it would not type.
