### ISSUE TITLE
Point to the appropriate stable version of the agda-stdlib doc instead of the dev one

### ISSUE THREAD

**Issue by gallais** [plfa/plfa.github.io#260]
Currently links to the standard library point to https://agda.github.io/agda-stdlib
which is the doc corresponding to the master branch of agda-stdlib.

IIUC the book is based on 0.17 so to avoid links pointing at the wrong thing,
you should instead use the https://agda.github.io/agda-stdlib/v0.17 version
of the doc.

**Comment by wenkokke** [comment]
Good point, thanks!

**Comment by wenkokke** [comment]
@gallais The link you included is quite dead, and none of the Agda stdlib pages seem to exist at that URL?

**Comment by gallais** [comment]
I screwed up the travis script trying to preserve the static versions of the older releases.

**Comment by wenkokke** [comment]
@gallais Can you let me know when they're (back) up?

**Comment by gallais** [comment]
They're back up but let's wait until after the build corresponding to the next merge
(probably at some point tomorrow). If they survive then it'll mean I really fixed it.

**Comment by gallais** [comment]
Victory!

**Comment by wenkokke** [comment]
Thanks 😂
