### ISSUE TITLE
Version mismatch

### ISSUE THREAD

**Issue by fangyi-zhou** [plfa/plfa.github.io#265]
I believe https://github.com/plfa/plfa.github.io/commit/d6ecb6a2e21996b358f019902138766eb09dc63a uses a different version of the standard library by import `_≟_` from `Data.String` instead of `Data.String.Unsafe`.

However travis did not complain, but looking at build logs the error is there:
https://travis-ci.org/plfa/plfa.github.io/builds/537301498
```
Checking PUC-Assignment3 (/home/travis/build/plfa/plfa.github.io/tspl/PUC-Assignment3.lagda).
 Checking plfa.Lambda (/home/travis/build/plfa/plfa.github.io/src/plfa/Lambda.lagda).
/home/travis/build/plfa/plfa.github.io/src/plfa/Lambda.lagda:56,13-24
The module Data.String doesn't export the following: _≟_
when scope checking the declaration
  open import Data.String using (String; _≟_)
```

**Comment by wenkokke** [comment]
Thanks @fangyi-zhou ! It'd just discovered that. We're in the process of rolling back those changes. I'm a little puzzled as to why travis didn't complain, however. If you have any ideas, please feel free to share them!

**Comment by fangyi-zhou** [comment]
I think when you pipe a command, the exit code is discarded.
e.g. `false | echo` has exit code 0 instead of 1.

Travis seems to cache `out` directory, so the old file is there. If there is a new error, sed will only complain if the file doesn't exists, but it can read the old cache and hence doesn't.
