### ISSUE TITLE
Definition for the ⊢ƛ typing judgment data constructor

### ISSUE THREAD

**Issue by mdimjasevic** [plfa/plfa.github.io#285]
In the introductory chapter on lambda calculus, the definition of [typing judgment](https://plfa.github.io/Lambda/#33420) has a data constructor for functions:

```agda
data _⊢_⦂_ : Context → Term → Type → Set where

  -- ⇒-I
  ⊢ƛ : ∀ {Γ x N A B}
    → Γ , x ⦂ A ⊢ N ⦂ B
      -------------------
    → Γ ⊢ ƛ x ⇒ N ⦂ A ⇒ B
```

Can you please clarify why does `x` of type `A` have to appear at the very end of the context? Wouldn't it suffice to say `Γ ∋ x ⦂ A`? I was expecting the definition for this data constructor to be something like this:

```agda
  -- ⇒-I
  ⊢ƛ : ∀ {Γ x N A B}
    → Γ ∋ x ⦂ A
    → Γ ⊢ N ⦂ B
      -------------------
    → Γ ⊢ ƛ x ⇒ N ⦂ A ⇒ B
```

**Comment by wenkokke** [comment]
The difference between the two definitions you've just given is that in your definition, x is *in* gamma, wheres in the PLFA definition, x is *added to* gamma.

**Comment by mdimjasevic** [comment]
I'll give an example later today to illustrate why I was expecting the alternative definition.

**Comment by wadler** [comment]
Good question. I've added a sentence to clarify: "Note also the three places (in ⊢ƛ, ⊢case, and ⊢μ) where the context is extended with x and an appropriate type, corresponding to the three places where a bound variable is introduced."
