### ISSUE TITLE
Naming: _—↠⟨_⟩_ instead of _—→⟨_⟩_

### ISSUE THREAD

**Issue by mdimjasevic** [plfa/plfa.github.io#325]
In the introductory chapter on lambda calculus, the `_—→⟨_⟩_` data constructor belongs to the `—↠` relation. Why does the name of the data constructor then have `—→` in it instead of `—↠`? Is the name as it is common in the literature?

**Comment by h4iku** [comment]
I think it's because each multi-step reduction consists of multiple single step reductions, and `_—→⟨_⟩_` recursively builds a `_—↠_` by reducing a term one step at a time as shown in its following examples.

**Comment by wenkokke** [comment]
@h4iku is right, you build multi-step reductions by composing a series of single-step reductions.

**Comment by mdimjasevic** [comment]
Ok, thank you both for clarifications!

**Comment by wadler** [comment]
Thanks to Marco for the original question, and to h4iku and Wen for answers.
