### ISSUE TITLE
Properties: definition of canonical form

### ISSUE THREAD

**Issue by mdimjasevic** [plfa/plfa.github.io#326]
In the chapter on properties, there is a section Canonical Forms. The prose there has no definition of what constitutes canonical form, the section only starts with this sentence: "Well-typed values must take one of a small number of canonical forms."

Should I make a pull request that adds a sentence or two giving a definition of canonical form?

**Comment by wadler** [comment]
Yes, please. (Sorry for the delay in response, buried in email!)
