### ISSUE TITLE
∃-even-odd

### ISSUE THREAD

**Issue by Boarders** [plfa/plfa.github.io#329]
If I try to do the same style of proof you have done for ∃-even and ∃-odd as follows:

```agda

postulate even-lemma-2 : ∀ (n : ℕ) ->  n + (n + zero) + 1 ≡ n + suc (n + zero)

∃-even : ∀ {n : ℕ} → ∃[ m ] (    2 * m ≡ n) → even n
 -- {-# NON_TERMINATING #-}
∃-odd  : ∀ {n : ℕ} → ∃[ m ] (2 * m + 1 ≡ n) →  odd n
∃-even ⟨ zero , refl ⟩ = even-zero
∃-even ⟨ suc m , refl ⟩ = even-suc (∃-odd ⟨ m , even-lemma-2 m ⟩)
∃-odd ⟨ n , refl ⟩ rewrite +-comm (n + (n + zero)) 1 = odd-suc (∃-even ⟨ n , refl ⟩)
```
Then the termination checker is unhappy. The exercise should probably indicate a different way forward or explain that it might be necessary. Unless you had something else in mind for the solution where the termination checker is less agitated.

**Comment by Boarders** [comment]
I should note that tomjack on the #agda irc pointed out that one can make the termination checker happier by using a curried version for the definitions as I have done [here](https://github.com/Boarders/plfa-exercises/blob/master/Quantifiers/Quantifiers.agda#L223).

**Comment by wadler** [comment]
Thanks. Do you want to draft some appropriate text?
