### ISSUE TITLE
Inaccurate statement about diamond proprety and confluence?

### ISSUE THREAD

**Issue by dkrejsa** [plfa/plfa.github.io#332]
In the chapter Lambda.lagda, there is a discussion of confluence and the 'diamond property'.  This subsection ends with the paragraph

    It is easy to show that every deterministic relation satisfies
    the diamond property, and that every relation that satisfies
    the diamond property is confluent.  Hence, all the reduction
    systems studied in this text are trivially confluent.

I do not think it is true that 'every relation that satisfies the diamond property is confluent.'
The Wikipedia page about [confluence (in abstract rewriting systems)](https://en.wikipedia.org/wiki/Confluence_(abstract_rewriting)) defines what the Lambda.lagda chapter calls the 'diamond property' as 'local confluence', and it gives a couple of examples (Pic. 3 and Pic. 4) of relations that are locally confluent but not globally confluent.  In the terms of the Lambda chapter, these would be relations that satisfy the diamond property but are not confluent.

The particular conclusion about deterministic relations being confluent is correct, just not fully supported by the given argument.

**Comment by wadler** [comment]
Ooops! Thanks for the correction. Usually, the diamond property is used to show confluence. So what additional property is required to make the statement correct?

**Comment by dkrejsa** [comment]
-- Given strong normalization, a relation that satifies the diamond
    -- (local confluence) property everywhere is also (globally) confluent
    -- everywhere.  This doesn't help our case, since the fixpoint (μ) terms
    -- prevent strong normalization from holding, but it is interesting.
    -- Note, I'm considering strong normalization to mean every element
    -- is accessible, with the notion Acc of accessibility defined below.

    open import Data.Product renaming (proj₁ to fst ; proj₂ to snd)

    data RTC {i j} {A : Set i} (r : A -> A -> Set j) : A -> A -> Set (i ⊔ j) where
       reflex : ∀ {x} -> RTC r x x
       step : ∀ {x} y {z} -> r x y -> RTC r y z -> RTC r x z

    transRTC : ∀ {i j} {A : Set i} (r : A -> A -> Set j) -> {x y z : A} ->
               RTC r x y -> RTC r y z -> RTC r x z
    transRTC r reflex rrxz = rrxz
    transRTC r (step t rxt rrty) rryz = step t rxt (transRTC r rrty rryz)

    meeting : ∀ {i j} {A : Set i} (r : A -> A -> Set j) (x y : A) -> Set (i ⊔ j)
    meeting {A = A} r x y = Σ A (λ z -> RTC r x z × RTC r y z)

    diamond : ∀ {i j} {A : Set i} (r : A -> A -> Set j) (L : A) -> Set (i ⊔ j)
    diamond {A = A} r L = ∀ {M N} -> r L M -> r L N -> meeting r M N

    confluent : ∀ {i j} {A : Set i} (r : A -> A -> Set j) (L : A) -> Set (i ⊔ j)
    confluent {A = A} r L = ∀ {M N} -> RTC r L M -> RTC r L N -> meeting r M N

    -- right-handed accessiblity for the relation r

    data Acc {i j} {A : Set i} (r : A -> A -> Set j) : A -> Set (i ⊔ j) where
       acc : ∀ {x} -> (∀ y -> r x y -> Acc r y) -> Acc r x

    acc-descend : ∀ {i j} {A : Set i} (r : A -> A -> Set j) {x y : A} ->
                  Acc r x -> RTC r x y -> Acc r y
    acc-descend r arx reflex = arx
    acc-descend r (acc f) (step v xv vrry) = acc-descend r (f v xv) vrry

    lem : ∀ {i j} {A : Set i} (r : A -> A -> Set j) ->
          (x : A) -> diamond r x ->
          ((y : A) -> r x y -> (z : A) -> RTC r y z -> confluent r z) ->
          confluent r x
    lem r x diax cbx reflex xN = _ , xN , reflex
    lem r x diax cbx (step y rxy yM) reflex = _ , reflex , step y rxy yM
    lem r x diax cbx (step y {M} rxy yM) (step v {N} rxv vN) = aux (diax rxy rxv)
    --             x
    --           /   \
    --          y     v
    --         / \   / \
    --        /   \ /   \
    --       M     z     N
    --        \   /  \   /
    --         \ /    \ /
    --          P      Q
    --           \    /
    --            \  /
    --             S
      where
        aux : meeting r y v -> meeting r M N
        aux (z , yz , vz) with cbx y rxy y reflex yM yz | cbx v rxv v reflex vz vN
        ... | (P , MP , zP) | (Q , zQ , NQ) with cbx y rxy z yz zP zQ
        ...                                    | (S , PS , QS) = S , transRTC r MP PS , transRTC r NQ QS

    lem2 : ∀ {i j} {A : Set i} (r : A -> A -> Set j) ->
          (x : A) -> diamond r x ->
          ((y : A) -> r x y -> (z : A) -> RTC r y z -> confluent r z) ->
          (z : A) -> RTC r x z -> confluent r z
    lem2 r x diax cbx .x reflex = lem r x diax cbx
    lem2 r x diax cbx z (step y {z} rxy yz) = cbx y rxy z yz

    acc-diamond-confluent' : ∀ {i j} {A : Set i} (r : A -> A -> Set j) ->
                              ((x : A) -> Acc r x -> diamond r x) ->
                              (x : A) -> Acc r x -> (y : A) -> RTC r x y -> confluent r y
    acc-diamond-confluent' r dia x (acc f) = lem2 r x (dia x (acc f)) cbx
      where
        cbx : ∀ y -> r x y -> ∀ z -> RTC r y z -> confluent r z
        cbx y rxy = acc-diamond-confluent' r dia y (f y rxy)

    -- If the diamond property holds at every accessible x, confluence also
    -- holds for every accessible x.

    acc-diamond-confluent : ∀ {i j} {A : Set i} (r : A -> A -> Set j) ->
                             ((x : A) -> Acc r x -> diamond r x) ->
                             (x : A) -> Acc r x -> confluent r x
    acc-diamond-confluent r dia x accx = acc-diamond-confluent' r dia x accx x reflex

    -- r is strongly normalizing if every x is accessible.

    strongly-normalizing : ∀ {i j} {A : Set i} (r : A -> A -> Set j) -> Set (i ⊔ j)
    strongly-normalizing r = ∀ x -> Acc r x

    strongly-normalizing-diamond-confluent : ∀ {i j} {A : Set i} (r : A -> A -> Set j) ->
                                             strongly-normalizing r ->
                                             ((x : A) -> diamond r x) ->
                                             ((x : A) -> confluent r x)
    strongly-normalizing-diamond-confluent r snr dia x = acc-diamond-confluent r (λ x _ -> dia x) x (snr x)

    -- It is a simple induction to show that any deterministic relation is confluent.
    -- Note, this makes no use of the diamond property.

    deterministic : ∀ {i j} {A : Set i} (r : A -> A -> Set j) -> Set (i ⊔ j)
    deterministic r = ∀ {x y z} -> r x y -> r x z -> y ≡ z

    deterministic-confluent : ∀ {i j} {A : Set i} (r : A -> A -> Set j) ->
                              deterministic r -> (∀ x -> confluent r x)
    deterministic-confluent r detr x reflex xN = _ , xN , reflex
    deterministic-confluent r detr x (step y rxy yM) reflex = _ , reflex , step y rxy yM
    deterministic-confluent r detr x (step y rxy yM) (step z rxz zN) with detr rxy rxz
    deterministic-confluent r detr x (step y rxy yM) (step .y rxy' yN)  | refl = deterministic-confluent r detr y yM yN
