### ISSUE TITLE
Generate anchor links to section title

### ISSUE THREAD

**Issue by gallais** [plfa/plfa.github.io#334]
The generated html has anchors corresponding to sections (e.g. [this link to
the 'Extensionality' header in `Isomorphism`](https://plfa.github.io/Isomorphism/#extensionality)) but there is no easy way for users
to grab a permalink to such an anchor (I got this one by inspecting the source
of the page).

You can see e.g. the `headerlink` class on readthedocs for inspiration: a
link appears when hovering on the RHS of a section title. Random link with a
section title demonstration this behaviour:
https://agda.readthedocs.io/en/v2.6.0.1/language/prop.html#the-predicative-hierarchy-of-prop

**Comment by wadler** [comment]
Thank you for the suggestion. I'll leave it to Wen. She has limited time, and this may not be the most important priority.
