### ISSUE TITLE
Any-∃ (Lists): Does the ∃[ x ∈ xs ] P x syntax work?

### ISSUE THREAD

**Issue by collares** [plfa/plfa.github.io#339]
I had to use `∃[ x ] (x ∈ xs × P x)`.

**Comment by collares** [comment]
Minimized testcase: https://gist.github.com/collares/fdf91795968f808b14dcd06f41e201bc

**Comment by wadler** [comment]
In the syntax you cite, what follows the ∈ is not a list but a type. The symbol ∈ is used in the standard library because a colon would be illegal.

record Σ {a b} (A : Set a) (B : A → Set b) : Set (a ⊔ b) where
  constructor _,_
  field
    fst : A
    snd : B fst
syntax Σ-syntax A (λ x → B) = Σ[ x ∈ A ] B

**Comment by collares** [comment]
I appreciate the answer. However, I couldn't get ∃-syntax or Σ-syntax to work in the context of exercise Any-∃ as stated (the initial workaround I mentioned works, though), where I believe  Googling tells me another person had the same problem in [0]. A link to the exercise is [1].

[0] https://stackoverflow.com/questions/56375003/what-is-a-valid-type-signature-for-the-any-%E2%88%83-exercise
[1] https://github.com/plfa/plfa.github.io/blame/dev/src/plfa/Lists.lagda.md#L1019 (I am linking to the blame version because that's the only way I know of linking to a specific line in a Markdown file).

**Comment by Boarders** [comment]
The problem here is there is a typo in the exercise.

```Show that Any P xs is isomorphic to ∃[ x ∈ xs ] P x.```

should instead read as:

```Show that Any P xs is isomorphic to  Σ[ x ∈ xs ] P x. ```

For example this type signature parses for me:
```agda
Any-∃ : {A : Set} {P : A -> Set} -> (xs : List A) ->
         Any P xs ≃ Σ[ x ∈ A ] P x
```

Note that we also need to import  Σ-syntax from Data.Product. I would be happy to fix this in a PR but unfortunately I have been unable to build the book locally and am unsure how you type check the .lagda.markdown files.

**Comment by collares** [comment]
This parses, but the right-hand side of the isomorphism doesn't mention the list xs. My question is then this, I guess: Wouldn't a proof of this imply that "Any P xs" is isomorphic to "Any P ys" for any two lists xs and ys, by transitivity?

**Comment by Boarders** [comment]
Oh sorry you are quite right, I was too hasty!

I actually needed:
```
Any-∃ : {A : Set} {P : A -> Set} -> (x : A) -> (xs : List A) -> (eq : x ∈ xs) ->
         Any P xs ≃ Σ[ x ∈ A ] P x
```

Apologies! In any case, looks like this is still an issue.

**Comment by Boarders** [comment]
Yes, sorry you are quite right!

**Comment by collares** [comment]
@wadler Should this be reopened, per the above comment/discussion? I can quickly send a one-line PR if so.
