### ISSUE TITLE
Menu overlaps content on mobile

### ISSUE THREAD

**Issue by h4iku** [plfa/plfa.github.io#347]
Menu overlaps on the title and some content of the book on smaller screens. Clicking on the menu icon also doesn't close it.

![Screen Shot 2019-07-16 at 23 55 02](https://user-images.githubusercontent.com/3812788/61326322-b7aae080-a82b-11e9-860b-a506f5347c85.png)

**Comment by wenkokke** [comment]
I'll have a look at the most recent version of jekyll/minima, see if they've made any changes. Otherwise this is a problem with the minima theme in general.

**Comment by wenkokke** [comment]
I can reproduce this on Android/Firefox and iOS/Safari.
