### ISSUE TITLE
Precedence not explained before usage

### ISSUE THREAD

**Issue by nomennescio** [plfa/plfa.github.io#362]
https://plfa.github.io/Relations/

"We set the precedence of _≤_ at level 4, so it binds less tightly than _+_ at level 6 "

Levels of precedence are not explained before use. Binding is not explained, although a bit intuitive.  The use of 'infix' to talk about association is quite loose.

**Comment by wadler** [comment]
Precedence is explained in chapter Naturals, section Precedence.

**Comment by nomennescio** [comment]
Indeed, I overlooked that section. I'm still missing an overview of precedence levels, is that available? Or, as a user, how can I discover the precedence of an operator?
