### ISSUE TITLE
Use of constructor either not explained or not defined

### ISSUE THREAD

**Issue by nomennescio** [plfa/plfa.github.io#363]
https://plfa.github.io/Relations/

"Here z≤n and s≤s (with no spaces) are constructor names, while zero ≤ n, and m ≤ n and suc m ≤ suc n (with spaces) are types. "

However, in the line:
inv-s≤s (s≤s m≤n) = m≤n

is 'm≤n' only a free variable, or is it a constructor, or does it relate to type of the argument of inv-s≤s? To me that is not clear from the text.

Similarly for:
≤-trans (s≤s m≤n) (s≤s n≤p)  =  s≤s (≤-trans m≤n n≤p)

Is this only a naming convention for the arguments?

**Comment by wadler** [comment]
Thanks. I added a sentence on the convention for variable names.
