### ISSUE TITLE
Suggestion: properly comment about zero as base case for Exponentiation on Part 1

### ISSUE THREAD

**Issue by mayconamaro** [plfa/plfa.github.io#384]
I know this can be quite controversial, but at part 1, chapter Naturals, the book formalizes the natural numbers using Peano's notation. Peano itself defined naturals starting at 1, reason why the base case for exponentiation would not lead into a problem. But since this book formalizes naturals starting at 0 and the exponentiation formulas are defined as

```
m ^ 0        =  1
m ^ (1 + n)  =  m * (m ^ n)
```
the base case indirectly asserts that 0 ^ 0 ≡ 1. This is considered indeterminate by some. I think it would be enriching to explicitly comment about this case on this formulation, since accepting 0 as a natural does not imply that 0 ^ 0 is 1.

**Comment by collares** [comment]
The book explicitly mentions that `0 ^ 0 ≡ 1` in chapter Negation, where they explain the rationale for doing so.

The concern you have stems from Calculus, I believe: If f and g tend to 0, then the limit f^g can be anything. The word "indeterminate" in this context means "indeterminate with regards to taking limits", and is a pedagogical device for teaching the rules of Calculus. However, not defining 0^0 to be equal to 1 complicates almost everything in Combinatorics, as described in Donald Knuth's "Two Notes on Notation", which I quote:

> [...] The debate stopped there, apparently with the conclusion that 0^0 should be undefined. 
>
> But no, no, ten thousand times no! Anybody who wants the binomial theorem [formula omitted due to typographical reasons] to hold for at least one nonnegative integer n must believe that 0^0 = 1, for we can plug in x = 0 and y = 1 to get 1 on the left and 0^0 on the right. 
>
> The number of mappings from the empty set to the empty set is 0^0. It has to be 1. 
>
> On the other hand, Cauchy had good reason to consider 0^0 as an undefined limiting form, in the sense that the limiting value of f(x)^g(x) is not known a priori when f(x) and g(x) approach 0 independently.
