### ISSUE TITLE
Suggestion: 'Renaming' should be renamed

### ISSUE THREAD

**Issue by dkrejsa** [plfa/plfa.github.io#386]
The Properties.lagda chapter contains a section on 'Renaming' with the result

    rename : ∀ {Γ Δ}
            → (∀ {x A} → Γ ∋ x ⦂ A → Δ ∋ x ⦂ A)
              ----------------------------------
            → (∀ {M A} → Γ ⊢ M ⦂ A → Δ ⊢ M ⦂ A)

However, it strikes me that nothing (i.e. no variables) are being renamed in this result.
The concept it embodies should instead be called 'context extension' or 'context refinement'
or something like that.

**Comment by dkrejsa** [comment]
"recontextualize" ;-)

**Comment by wenkokke** [comment]
`rename` does in fact performs renaming – the free variables 0, 1, 2, 3, ..., len(Γ) are renamed using the names 0, 1, 2, 3, ..., len(Δ).

**Comment by dkrejsa** [comment]
That would actually be renumbering, but OK.
