### ISSUE TITLE
Changes to the book not taking effect on the website

### ISSUE THREAD

**Issue by h4iku** [plfa/plfa.github.io#393]
Changes to the book after restructuring are not taking effect on the website. Older files [still exist](https://github.com/plfa/plfa.github.io/tree/master/out/plfa), and they are being served instead of the new ones.
Only Chapter [BigStep](https://plfa.github.io/BigStep/) has the new structure of the book at the moment because it was renamed from [CallByName](https://plfa.github.io/CallByName/), which still exists.

I am reporting this since I thought it might not be intentional.

**Comment by wenkokke** [comment]
Thanks! This is a problem with the caching mechanism, I suppose.

**Comment by h4iku** [comment]
It's all good now.
