### ISSUE TITLE
extrinsically vs intrinsically-typed line count

### ISSUE THREAD

**Issue by chikeabuah** [plfa/plfa.github.io#403]
the authors claim that the intrinsically-typed lambda calculus representation has less lines, but in the accompanying graphic it is shown as having more lines (275 > 216)

<img width="767" alt="Screen Shot 2019-09-16 at 10 11 09 AM" src="https://user-images.githubusercontent.com/2280440/64965162-7d30e480-d86a-11e9-80dd-d76fff11f9ec.png">

**Comment by wadler** [comment]
(216 + 235) / 275 = 1.6

**Comment by chikeabuah** [comment]
my mistake, thank you!
