### ISSUE TITLE
Lists: A slight change of the exercise `reverse-++-commute`

### ISSUE THREAD

**Issue by AD1024** [plfa/plfa.github.io#412]
First, since the operation `reverse` together with `++` on two lists is not commutative, would the name `reverse-++-distrib` be more precise about the exercise?

Second, the parameter `{xs ys : List A}`could be changed to explicit parameter since to solve the problem we need to do induction on a list, and it makes the solution more concise while including the induction hypothesis.

**Comment by wenkokke** [comment]
> First, since the operation `reverse` together with `++` on two lists is not commutative, would the name `reverse-++-distrib` be more precise about the exercise?

It seems like the proper term could be antidistributivity?

> The ubiquitous identity that relates inverses to the binary operation in any group, namely (xy)−1 = y−1x−1, which is taken as an axiom in the more general context of a semigroup with involution, has sometimes been called an antidistributive property (of inversion as a unary operation).
> <https://en.wikipedia.org/wiki/Distributive_property#Notions_of_antidistributivity>

**Comment by wenkokke** [comment]
> Second, the parameter `{xs ys : List A}`could be changed to explicit parameter since to solve the problem we need to do induction on a list, and it makes the solution more concise while including the induction hypothesis.

Eh, it's a matter of taste, really. If you find that using this proof you need to fill in the implicit parameters more often than not, they should be made explicit. I think this is a good candidate for that, but I'm not very fussed. We could call it an opportunity to practice pattern matching on implicit parameters.

**Comment by wadler** [comment]
Thank you for these suggestions, Mike. They sound good to me. If you submit a pull request that implements them, I will approve.
