### ISSUE TITLE
Suggestion: add the law of contraposition to the exercise in chapter Negation

### ISSUE THREAD

**Issue by jllang** [plfa/plfa.github.io#421]
In the exercise Classical (stretch), the law of contraposition, i.e. `\forall {A B : Set} \r (\neg B \r \neg A) \r (A \r B)` could be added to the list of classical laws to be proven equivalent. The converse is intuitionistically valid. I found straightforward proofs in Agda showing that material implication and double negation elimination together imply the law of contraposition, which implies the law of the excluded middle.

**Comment by wadler** [comment]
Good point. The five statements currently there can be proved circularly. If contraposition was added, is there a position that would maintain the possibility of circular proof? Where?

**Comment by jllang** [comment]
I haven't even managed to find circular proofs for the five statements. I have shown that LEM and material implication are equivalent, and that LEM implies double negation elimination, which implies de Morgan's law, which implies LEM. Peirce's law also implies LEM, but I needed both the material implication and double negation elimination for proving Peirce's law.
