### ISSUE TITLE
Problem in Exercise ∀-× (practice), chapter Quantifiers

### ISSUE THREAD

**Issue by jllang** [plfa/plfa.github.io#422]
I'm sorry if this sounds more like a question about Agda than PLFA, but I feel like I've run into some subtle issue by trying to follow this exercise in what I believe to be the obvious way. I understood that the task in this exercise is to prove the following:
```∀-× : ∀ {B : Tri → Set} → (∀ (x : Tri) → B x) ≃ B aa × B bb × B cc```
I proved the following lemmas:
```
lemma-3 : ∀ {B : Tri → Set}
  → ((x : Tri) → B x)
    ------------------
  → B aa × B bb × B cc
lemma-3 f = ⟨ f aa , ⟨ f bb , f cc ⟩ ⟩

lemma-4 : ∀ {B : Tri → Set}
  → B aa × B bb × B cc
    ------------------
  → ((x : Tri) → B x)
lemma-4 ⟨ baa , ⟨ _ , _ ⟩ ⟩ aa = baa
lemma-4 ⟨ _ , ⟨ bbb , _ ⟩ ⟩ bb = bbb
lemma-4 ⟨ _ , ⟨ _ , bcc ⟩ ⟩ cc = bcc
```
`lemma-3` and `lemma-4` correspond with the `to` and `from` parts of the isomorphism record respectively. I managed to prove `from∘to` after some thinking. However, with `to∘from`, I can't even spell out my claim without getting errors from Agda. What could be the issue here?

**Comment by wadler** [comment]
Github is not intended as a discussion forum for those having problems with PLFA exercises. There are plenty of other places to try, or if you set up your own forum we can add a link to the PLFA contents page.
