### ISSUE TITLE
Make Lambda plusᶜ slightly more clear

### ISSUE THREAD

**Issue by qaisjp** [plfa/plfa.github.io#434]
There's a part of this (Lambda) chapter that I had to read several times to understand what was going on, copied here:

> Addition takes two numerals `m` and `n`, a function `s` and an argument `z`, and it uses `m` to apply `s` to the result of using `n` to apply `s` to `z`; hence `s` is applied `m` plus `n` times to `z`, yielding the Church numeral for the sum of `m` and `n`.

It's clear how it works once you remember the very important fact that:

> the number _n_ is represented by a function that accepts two arguments and applies the first _n_ times to the second

Whilst it may be obvious, I feel that the first quote would be easier to consume if it was reworded a little bit to highlight _how many_ times `s` is applied, something like this:

> By the definition of `n`, `` ` "n" · ` "s" · ` "z"`` applies `s` _n_ times to `z`, giving us the number _n_. Then, `s` is applied `m` times to this result (_n_), giving us `m` plus `n`. Hence `s` is applied `m` plus `n` times to `z`.

**Comment by wadler** [comment]
Exactly the sentence you request appears in the preceding paragraph.
