### ISSUE TITLE
DeBruijn: Discuss "rename _ _ = μ ` Z"?

### ISSUE THREAD

**Issue by collares** [plfa/plfa.github.io#439]
In chapter DeBruijn, "μ ` Z" is a valid term of any type in any context, and it is found by Agsy. Therefore, there are easy-to-find wrong implementations of "rename"  that typecheck. Is this worth discussing?

**Comment by wenkokke** [comment]
I don't think this is worth discussing. The term ``μ ` Z`` represents an infinite loop, so this is true for any operation on terms, not just `rename`. However, "replace whatever with an infinite loop" is pretty clearly the wrong operation. Furthermore, I would discourage readers from overly relying on Agsy.
