### ISSUE TITLE
Mentioning quail-show-key and  agda-input-show-translations

### ISSUE THREAD

**Issue by ywata** [plfa/plfa.github.io#448]
Hi. 

I found two useful emacs command to input math symbols.
They are quail-show-key and  agda-input-show-translations. 
I'd like to propose to mention these commands somewhere on the top of web page or in the book.

M-x qual-show-key
If you type the command on mathematical symbol in agda-mode, emacs gives you how you input the symbol in mini buffer.

M-x agda-input-show-translations
This command seems to show you all the possible math symbol in agda mode.

As I forgot how I input some math symbols after some break period, these are very useful to me.

**Comment by wadler** [comment]
OK. Please write a pull request to add these under "Unicode Characters" on the "Getting Started" page. You might also want to copy them to the Unicode section at the end of Chapter Naturals.

**Comment by ywata** [comment]
OK. Then, I'll also check some more useful emacs commands for math symbols exist or not before I write pull request.

**Comment by ywata** [comment]
As my pull request was merged. I close this ticket.
Thank you. I hope this helps PLFA readers.
