### ISSUE TITLE
Dead link?

### ISSUE THREAD

**Issue by hanshuttel** [plfa/plfa.github.io#466]
There appears to be a problem with a dead link. See below.

`iMac% make test
Processing courses/tspl/2019/Assignment2.lagda.md
./highlight.sh courses/tspl/2019/Assignment2.lagda.md --include-path=src/ --include-path=courses/tspl/2019/
courses/tspl/2019/Assignment2.lagda.md: canonicalizePath: does not
exist (No such file or directory)
File not generated: 
make: *** [out/tspl/2019/Assignment2.md] Error 1`

**Comment by wadler** [comment]
Wen? Do you know what's going on here? My laptop isn't setup for Agda currently, so it's difficult for me to try this out.

**Comment by wenkokke** [comment]
Can't replicate this myself, so I'm not sure what's going on.
