### ISSUE TITLE
Solution for `.lagda.md` not being supported by many editors / IDEs

### ISSUE THREAD

**Issue by razvan-flavius-panda** [plfa/plfa.github.io#475]
About 1-2 years ago PLFA was using `.lagda` files and at some point it moved to using `.lagda.md` files.

`.lagda.md` files are not well supported on most editors or IDEs. For example, they do not work in Atom, Visual Studio Code, etc.

From what I heard `.lagda.md` do work when using `agda-mode` in any Emacs variant, like vanilla, Spacemacs, Doom Emacs, etc. but I have not tested this.

Possible solutions:

* forcing everyone to use only editors or IDEs that work with `.lagda.md`
* create a `.lagda.md` <-> `.lagda` isomorphism implementation and use it to translate between them so that editors can just use `.lagda` which they support

Any other suggestions or possible solutions to this problem?

**Comment by razvan-flavius-panda** [comment]
We have started doing a PLFA study and we are quite a few people but stumbled upon this issue that blocks us.

**Comment by wenkokke** [comment]
Agda switched to using this extension as part of their push to support different sorts of literate code, starting with version 2.6.0. The purpose of using this extension was to trigger the editor mode for the literate text, as opposed to the editor for Agda. In emacs, we offer a workaround, which essentially special-cases `.lagda.md` and opens `agda-mode` for it. However, for other IDEs similar solutions may not exist.

What you could try is symlinking each `.lagda.md` file to a `.lagda` file, and directing students to open the symlinks instead? That way, the editor sees the `.lagda` extension, without actually changing PLFA?

**Comment by razvan-flavius-panda** [comment]
@wenkokke Thank you for the timely reply.

Could you give more detailed steps into how to do this and how it would work? `What you could try is symlinking each .lagda.md file to a .lagda file, and directing students to open the symlinks instead?`

**Comment by wadler** [comment]
On Unix,
  ln -s file.lagda.md file.lagda
You'll have to look it up for Windows.

**Comment by razvan-flavius-panda** [comment]
@wenkokke @wadler I understand how symlinks work.

What I do not understand is: how will this get the editors working?

**Comment by wenkokke** [comment]
Oh, the trick is that the editor will see the `.lagda` extension as opposed to the `.lagda.md` extension, and load the appropriate editing mode.

(If your problem is that the editing modes don't support the Markdown code fences, obviously this won't address your problem.)

**Comment by wenkokke** [comment]
> From what I heard `.lagda.md` do work when using `agda-mode` in any Emacs variant, like vanilla, Spacemacs, Doom Emacs, etc. but I have not tested this.

Unrelated, but I use Spacemacs, and it works for me. The `agda-mode` ships with Agda, and hence it should be independent of Emacs variant.

**Comment by freeman42x** [comment]
Visual Studio Code has added support for `.lamba.md` 🥳
