### ISSUE TITLE
Integrate epubcheck into the build process

### ISSUE THREAD

**Issue by mreed20** [plfa/plfa.github.io#483]
Shouldn't be too hard. I can look into it if no one else beats me to it.

**Comment by wenkokke** [comment]
This shouldn't be too hard at all, assuming a debian package is available. However, we can't actually do this until we've gotten rid of all the errors.

**Comment by wenkokke** [comment]
Once the acknowledgements file is fixed, I plan to integrate epubcheck into the build process, make the resulting EPUB available on the website, and publicise the experimental support for the EPUB format.

**Comment by mreed20** [comment]
> Once the acknowledgements file is fixed, I plan to integrate epubcheck into the build process, make the resulting EPUB available on the website, and publicise the experimental support for the EPUB format.

That sounds great! Call me excited :)

**Comment by wenkokke** [comment]
Fixed!
