### ISSUE TITLE
Explain unnamed arguments

### ISSUE THREAD

**Issue by wenkokke** [plfa/plfa.github.io#486]
The first use of an unnamed argument is here: https://plfa.github.io/Relations/#transitivity
However, the syntax isn't explained... and in fact, `_` is explicitly ruled out (erroneously, but perhaps for the best) as a character that may occur in an Agda name.
We should probably address this.

**Comment by wadler** [comment]
What do you mean by "unnamed argument"? If you mean _, it is explained in the text. If you mean implicit arguments, they are explained in a section earlier.

**Comment by wenkokke** [comment]
Oh, so it is! I must've read over that.
