### ISSUE TITLE
Definition of Confluence in chapter Lambda (Part 2)

### ISSUE THREAD

**Issue by possientis** [plfa/plfa.github.io#488]
I just wanted to say that I was confused (and surprised) by the definition of `confluence` (and likewise of`diamond`) which you have given. Denoting `~>` the reduction relation, I was expecting a statement of the form:

`forall (L M N:Term), (L ~> M) -> (L ~> N) -> exists (P:Term), (M ~> P) /\ (N ~> P)`

but instead, your definition is (essentially) as follows:

`forall (L M N:Term), exists (P:Term), (L ~> M) -> (L ~> N) ->  (M ~> P) /\ (N ~> P)`

and in general these two statements are not equivalent. However, if the type `Term` is not empty and the relation `~>` is decidable, the two statements are in fact equivalent.

 The book (at that point) does not discuss the whether `~>` is decidable (I think it is but not totally sure yet), so as a newbie reader I am confused by your choice of definition. Just wanted to let you know this feedback.

Otherwise enjoying the book very much :)

**Comment by jsiek** [comment]
Dear possientis,

I agree that what you expected is preferable to the later definition you give above.
However, I'm confused because it seems to me that the Confluence chapter already
matches your expectation. For example, here's the statement of confluence at the
bottom of the chapter. Could you clarify where you saw the issue?

confluence : ∀{Γ A} {L M₁ M₂ : Γ ⊢ A}
  → L —↠ M₁
  → L —↠ M₂
    -----------------------------------
  → Σ[ N ∈ Γ ⊢ A ] (M₁ —↠ N) × (M₂ —↠ N)
confluence L↠M₁ L↠M₂
    with par-confluence (betas-pars L↠M₁) (betas-pars L↠M₂)
... | ⟨ N , ⟨ M₁⇛N , M₂⇛N ⟩ ⟩ =
      ⟨ N , ⟨ pars-betas M₁⇛N , pars-betas M₂⇛N ⟩ ⟩

Cheers,
Jeremy

**Comment by possientis** [comment]
Hi Jeremy,

I am looking at the page:
https://plfa.github.io/Lambda/

where I see:

```
confluence : ∀ {L M N} → ∃[ P ]
  ( ((L —↠ M) × (L —↠ N))
    --------------------
  → ((M —↠ P) × (N —↠ P)) )
```
I cannot see the snippet you are referring to so I am now guessing that the issue has already been corrected and I should not be following that page which is out of date ?

**Comment by wenkokke** [comment]
Heya @possientis! I think that Jeremy is referring to the [Confluence](https://plfa.github.io/Confluence/) chapter, in which we discuss confluence of the _untyped_ lambda calculus.

**Comment by possientis** [comment]
ah ok yes I can see it, thank you @wenkokke . So maybe my source is not out of date after all : )
Ok so I was referring to https://plfa.github.io/Lambda/.

**Comment by wenkokke** [comment]
@wadler: @possientis makes a good point, I think I'll update the pseudo-definitions of confluence and diamond in [Lambda](https://plfa.github.io/Lambda/).

**Comment by wenkokke** [comment]
@possientis: the section you're referring to *does* mention that the reduction system in question is deterministic, in which case the two definitions for confluence do coincide, since we can pick either M or N for P, and then use determinisim to show that they're equal.

**Comment by possientis** [comment]
@wenkokke good point, I think is is correct, I could prove equivalence using determinism. Thank you.

**Comment by possientis** [comment]
Guys, I am very sorry to come back, but I have the feeling that while the existing PR is an improvement, the statement contained within the final text i.e. 'every relation that satisfies the diamond property is confluent' is actually not true.  After trying to prove this for a few days, I did some research online and found:
https://en.wikipedia.org/wiki/Abstract_rewriting_system
It seems to me this wiki page is using the term 'locally confluent'  or 'weak confluence' as a synonym for 'having the diamond property' and it states: "Local confluence on the other hand is not equivalent with the other notions of confluence given in this section, but it is strictly weaker than confluence". It also provides the counter-example of a relation with a diamond property which is not confluent `{b -> c, c -> b, b -> a, c -> d}`
