### ISSUE TITLE
 Determinism for DeBruijn

### ISSUE THREAD

**Issue by wenkokke** [plfa/plfa.github.io#491]
In the chapter DeBruijn, we mention "We omit the proof that reduction is deterministic, since it is tedious and almost identical to the previous proof." However, the previous proof is progress, and the two are not almost identical. The previous chapter states the theorem for determinism, but does not prove it, so it is unlikely that it is this proof that is being referred to either. Did we remove the proof for determinisim from the chapter Lambda, and forget to update DeBruijn?

**Comment by wadler** [comment]
Chapter Properties contains a proof that reduction is deterministic:
https://plfa.github.io/Properties/#reduction-is-deterministic

**Comment by wenkokke** [comment]
Ah! Thanks for clearing that up.
