### ISSUE TITLE
Change spacing policy of PLFA

### ISSUE THREAD

**Issue by wenkokke** [plfa/plfa.github.io#505]
Currently, PLFA is written using `auto-fill-mode` enforcing a line-length limit of 80 characters. This is far from ideal for prose, and not at all what we want for Agda code. We should move to a policy _one line_ for every paragraph, which works well with line diffs, and avoids introducing issues such as #498 and #500.

**Comment by jsiek** [comment]
But there is a major problem with the suggested approach, which is that it is much less readable in Emacs :(

**Comment by wenkokke** [comment]
For me, the readability isn't really a problem, since Emacs automatically wraps lines after a certain length, and my buffers don't tend to be too wide? However, it does lead to problems for me where the lines get harder to navigate. I think it's worth the trade-off, though: Markdown is generally layout-sensitive, and so, as we've noticed, `auto-fill-mode` can easily introduce rendering errors.

**Comment by jsiek** [comment]
Nod

**Comment by wenkokke** [comment]
This was rejected by @wadler.
