### ISSUE TITLE
Move plfa.agda-lib or plfa/* to src/?

### ISSUE THREAD

**Issue by juhp** [plfa/plfa.github.io#511]
While looking at Fedora Agda packaging, I started wondering about `plfa.agda-lib`...
(admittedly this is untested so forgive me if I am completely wrong/off the mark here).

`plfa.agda-lib` references `src/` but the library modules actually live in `src/plfa/`.
So I am wondering if it should have `include: src/plfa` instead?
Unless agda is clever enough to look in plfa/ by itself?
Alternatively maybe the library modules could just live directly in `src/`?

**Comment by wenkokke** [comment]
@juhp: No, since all the module names are prefixed with `plfa`, e.g., `plfa.part2.DeBruijn`. I didn't want them to pollute the top-level module namespace.

**Comment by juhp** [comment]
That makes complete sense, thanks!
