### ISSUE TITLE
.dir-locals.el doesn't work

### ISSUE THREAD

**Issue by plumenator** [plfa/plfa.github.io#516]
The current .dir-locals.el breaks emacs (v28):

```elisp
dir-locals-read-from-dir: Wrong type argument: listp, turn-off-auto-fill
```

My understanding is that you can't call functions in .dir-locals.el. It's meant for variables.

**Comment by plumenator** [comment]
This seems relevant:
https://stackoverflow.com/questions/16237506/wrong-type-argument-listp-eval-after-load-in-dir-locals-el

**Comment by wenkokke** [comment]
Hm, good point. I'm just gonna go ahead and remove the `.dir-locals.el` file, and leave it to others to configure their emacs.
