### ISSUE TITLE
Part 1 - Equality chapter - Proving transitivity using ≡-Reasoning is circular

### ISSUE THREAD

**Issue by crisoagf** [plfa/plfa.github.io#547]
Hi! I am having a lot fun reading PLFA and following with the exercises. It's great!

However, while I was reading the Equality chapter something rubbed me the wrong way. ≡-Reasoning is defined, and then the first thing that is done is using ≡-Reasoning to prove transitivity of ≡.
However, ≡-Reasoning requires transitivity, so this could never be the actual definition of `trans`, and in no place is this even mentioned.
Would it be reasonable to mention this (or add an exercise to think about this)?

**Comment by wadler** [comment]
Good point! Yes, please make a pull request.

**Comment by crisoagf** [comment]
On it.

**Comment by crisoagf** [comment]
🎉🎉🎉
