### ISSUE TITLE
Am I not supposed to post solutions to the exercises in a public place?

### ISSUE THREAD

**Issue by ShreckYe** [plfa/plfa.github.io#549]
In the "Exercises" section of [the preface of Software Foundations](https://softwarefoundations.cis.upenn.edu/lf-current/Preface.html) it says:

> Please do not post solutions to the exercises in a public place.

Is this also true for this book? If so, I think it should be stated somewhere obvious in this book too, because I myself created a public GitHub repository to store my solutions when I started learning this book (now it's made private) and I can find some other GitHub `plfa-exercise` repos that contain solutions too.

**Comment by wadler** [comment]
Good point. Added this line to the end of the preface.

**Comment by wadler** [comment]
Thanks! I added the suggested line to the end of the preface.
