### ISSUE TITLE
Turn implicit argument into explicit in BigStep.lagda.md

### ISSUE THREAD

**Issue by xekoukou** [plfa/plfa.github.io#552]
This is one of the weird things about agda that still confuses me and making it into an explicit argument saves us from thinking about it. (I think that it eagerly tries to find the value of the implicit when we need a lambda instead.)

https://github.com/plfa/plfa.github.io/blame/dev/src/plfa/part2/BigStep.lagda.md#L189
https://github.com/plfa/plfa.github.io/blame/dev/src/plfa/part2/BigStep.lagda.md#L297

**Comment by jsiek** [comment]
I’m Ok with making that into an explicit argument. I don’t recall having
a specific reason to make it implicit.

Cheers,
Jeremy

**Comment by wenkokke** [comment]
@jsiek Have you made the suggested change?

**Comment by jsiek** [comment]
I had not, but now I have! Thanks for the ping.
