### ISSUE TITLE
Standard library setup for PLFA

### ISSUE THREAD

**Issue by ajrouvoet** [plfa/plfa.github.io#554]
The current setup is to ask students to edit their library file.
Has it been considered to instead provide the following `plfa.agda-lib`, so that no manual set up is necessary:

```
name: plfa
include: 
  - ./src/
  - ./standard-library/src/
```

Or am I missing a downside to this setup?

**Comment by wadler** [comment]
Good suggestion. Wen, what do you think?

**Comment by iblech** [comment]
Also, for setting up the PLFA in the Agdapad, I noticed that plfa works just fine with the current version of the standard library, version 1.5! Perhaps this fact should also be recorded (or was it a mirage?), and people who already have a well-functioning standard library setup can skip checking out their own copy in ./standard-library. :-)

**Comment by wenkokke** [comment]
> The current setup is to ask students to edit their library file.
> Has it been considered to instead provide the following `plfa.agda-lib`, so that no manual set up is necessary:
> 
> ```
> name: plfa
> include: 
>   - ./src/
>   - ./standard-library/src/
> ```
> 
> Or am I missing a downside to this setup?

I think this may result in errors if the student has an installation of the standard library on their system, which is listed in the defaults?

**Comment by ajrouvoet** [comment]
The documentation reads as if the defaults are only used if no explicit `.agda-lib` file is found.

```
- No explicit --library flag, and no .agda-lib file in the project root.
In this case the file AGDA_DIR/defaults is read and all libraries listed are added to the path.
The defaults file should contain a list of library names, each on a separate line.
In this case the current directory is also added to the path.

To disable default libraries, you can give the flag --no-default-libraries.
To disable using libraries altogether, use the --no-libraries flag.
``` 

https://agda.readthedocs.io/en/v2.6.1.1/tools/package-system.html#default-libraries

**Comment by wenkokke** [comment]
That helps, but I'm still a little worried what would happen if the students moved the exercises elsewhere, say out of the PLFA directory. We've frequently had students just download the solitary exercise files from the website, or even just copy-paste it into a fresh buffer. That works when your global install is properly setup, including a properly setup defaults file. However, it fails when we use your suggestion.

That aside, there might also be some value in students learning about the ~/.agda/ files?

**Comment by ajrouvoet** [comment]
> However, it fails when we use your suggestion.

That is a fair point. If it comes down to this point vs. the least number of manual steps in the setup I personally tend towards the latter. Perhaps because 20% of students will simply overlook the instruction. There were also a lot of students using Windows that had trouble with paths.

> That aside, there might also be some value in students learning about the ~/.agda/ files?

Perhaps, although it may be wishful thinking that any setup knowledge will stick while students are just trying to get started :)
I may be a little biased against the global setup in the `.agda` directory.

**Comment by GetContented** [comment]
Whatever is done, it would be nice if the "golden path" worked well.

**Comment by wenkokke** [comment]
Using this set up, what would happen if a student started working on an assignment somewhere outside of the scope of the PLFA project? I believe that for that common use case we would still have to require them to set up a libraries and a defaults file, in which case the conflict with an existing standard library would suddenly start breaking things…

**Comment by wenkokke** [comment]
I am closing this issue for now, but feel free to reopen it and comment with any other suggestions that might work well.

**Comment by wadler** [comment]
Wen and I have revised the README, and will republish the new version soon. (Various updates to CI required first.) We've taken on board the original suggestion. Thank you!
