### ISSUE TITLE
README.md nats.agda test can fail if created in the root of PLFA

### ISSUE THREAD

**Issue by ajrouvoet** [plfa/plfa.github.io#555]
If you create the suggested `nats.agda` in the root of PLFA or in the root of `standard-library`, then Agda will complain that the module is in the wrong place. Since the guide operates from the root, this is a likely mistake.

**Comment by ajrouvoet** [comment]
Other students create the file outside of the project entirely, in which case they (naturally) run into missing libraries.
I'll submit a PR that specifies the location for the file.

**Comment by GetContented** [comment]
This also happens when checking if Agda is installed properly, as the instructions guide us to do. It fails for the same reason, obviously.

IMO, the instructions should guide us, instead, to add the files to the `src` folder. It's what the error suggests we do, and it works well.

The following is the error given, if it helps.

```
➜  plfa git:(dev) ✗ agda -v 2 hello.agda
/Users/getcontented/code/agda/plfa/hello.agda:1,8-13
The name of the top level module does not match the file name. The
module hello should be defined in one of the following files:
  /Users/getcontented/code/agda/plfa/standard-library/src/hello.agda
  /Users/getcontented/code/agda/plfa/standard-library/src/hello.lagda
  /Users/getcontented/code/agda/plfa/src/hello.agda
  /Users/getcontented/code/agda/plfa/src/hello.lagda
  /Users/getcontented/code/agda/agda/.stack-work/install/x86_64-osx/2ea356db11ab153a6ba147b7da51aa71a671fd44c574cb318e18fbe51bafd587/8.8.3/share/x86_64-osx-ghc-8.8.3/Agda-2.6.1.3/lib/prim/hello.agda
  /Users/getcontented/code/agda/agda/.stack-work/install/x86_64-osx/2ea356db11ab153a6ba147b7da51aa71a671fd44c574cb318e18fbe51bafd587/8.8.3/share/x86_64-osx-ghc-8.8.3/Agda-2.6.1.3/lib/prim/hello.lagda
```

**Comment by wenkokke** [comment]
@ajrouvoet The library file has been migrated into the `src` directory, which I believe should solve this problem, at least for the case where the students put these files in the project root.
