### ISSUE TITLE
Submodules use ssh urls rather than https

### ISSUE THREAD

**Issue by ajrouvoet** [plfa/plfa.github.io#556]
Students run into the fact that the .gitmodules file uses an ssh url for the standard-library. This requires them to have an SSH identity set up. This might not be the case, for example on windows using WSL.

Would the `https` url not be a better default for the standard-library? Since few/no-one needs push permissions on it anyway?

**Comment by rudynicolop** [comment]
> Students run into the fact that the .gitmodules file uses an ssh url for the standard-library. This requires them to have an SSH identity set up. This might not be the case, for example on windows using WSL.
> 
> Would the `https` url not be a better default for the standard-library? Since few/no-one needs push permissions on it anyway?

I second this proposal. The [installation instructions](https://github.com/plfa/plfa.github.io#install-plfa-and-the-agda-standard-library) in the `README.md` are misleading b/c the `https` method does not work and the `ssh` one does. I suggest changing the cloning instructions to reflect this.

**Comment by wenkokke** [comment]
Fixed in 43bdaa94f47eeffdca92f5efe45ecc76476f651f.
