### ISSUE TITLE
PLFA-in-a-box

### ISSUE THREAD

**Issue by ajrouvoet** [plfa/plfa.github.io#559]
Dear PLFA authors,

For my course I've prepared an Ubuntu virtual machine with stack, Agda 2.6.1.1, latest PLFA, stdlib, and emacs + vscode ready to go. My idea was to publish this to Zenodo. Two questions:

- Is this OK with the PLFA team? 
- And if so, do you want to be named as co-authors of this artifact.

**Comment by wadler** [comment]
Arjen,

Thank you for putting this package together, I'm sure some folk will find
it helpful. As to authorship, I think it is clear that you are the author
of the package and the authors of PLFA are it's authors, and I'm happy to
leave it to you as to the best way to make that clear. It would be bad to
suggest that you were an author of PLFA or that its authors are not. Wen
and Jeremy, what do you think?

Go well, -- P


.\ Philip Wadler, Professor of Theoretical Computer Science
./\ School of Informatics, University of Edinburgh
/  \ http://homepages.inf.ed.ac.uk/wadler/

**Comment by jsiek** [comment]
-Jeremy

> On Feb 12, 2021, at 4:25 AM, Philip Wadler <notifications@github.com> wrote:
> 
> ﻿
> Arjen,
> 
> Thank you for putting this package together, I'm sure some folk will find
> it helpful. As to authorship, I think it is clear that you are the author
> of the package and the authors of PLFA are it's authors, and I'm happy to
> leave it to you as to the best way to make that clear.

I agree

**Comment by ajrouvoet** [comment]
The artifact can be found at the stable URL https://doi.org/10.5281/zenodo.4527308
If anyone tries it out and has suggestions for improvement, please let me know.
