### ISSUE TITLE
standard library links 404

### ISSUE THREAD

**Issue by jmchapman** [plfa/plfa.github.io#560]
If you click on a definition/import from the standard library in the code you get a 404 error.

E.g., click on  Relation.Binary.PropositionalEquality in https://plfa.github.io/Naturals/.

I think it's nice to link to the 'real' standard library docs but this is the downside I guess, they may move.

By default I think agda generates html for your code and any library code which you can self host.

**Comment by wadler** [comment]
Yes, we've had an issue for a while that links to the standard library are broken. Wen, what can we do about this?

**Comment by wenkokke** [comment]
Should be fixed once I publish a new version. Don't know how it got the idea we were on version 1.6?
