### ISSUE TITLE
Agda meets "Heap exhausted" problem when verifing 2*2=4 (Exercise mul-example) in chapter DeBruijin

### ISSUE THREAD

**Issue by wrvsrx** [plfa/plfa.github.io#583]
When I do Exercise mul-example in chapter DeBruijin, agda takes minutes to verify following codes (appending them after https://github.com/plfa/plfa.github.io/blob/dev/src/plfa/part2/DeBruijn.lagda.md), and then it says "Heap exhausted". 

My agda version is 2.6.2. I don't know if it's becase of agda itself or the implement of `mul`.

Edited. Remove the solution.

```
Process exited with code 251
agda: Heap exhausted;
agda: Current maximum heap size is 3758096384 bytes (3584 MB).
agda: Use `+RTS -M<size>' to increase it.
```

**Comment by wadler** [comment]
Works fine on my machine, normalising after 37 steps. Maybe your heap is too small?

Please remember not to post solutions to problems in public places.

**Comment by wrvsrx** [comment]
Sorry, I have removed the solution. It passes examination after I expand the heap size to 8G, thanks for your advice!

It seems a bug in agda (https://github.com/agda/agda/issues/4044) causes such huge memory cost and it hasn't been fixed.
