### ISSUE TITLE
part1/List: every parameterised type is claimed covariant

### ISSUE THREAD

**Issue by lorenzo-lipparini** [plfa/plfa.github.io#584]
As it was discussed on [Agda Zulip](https://agda.zulipchat.com/#narrow/stream/259644-newcomers/topic/Plfa.3A.20every.20parameterised.20type.20claimed.20covariant), the following paragraph from [chapter part1/List section Map](https://plfa.github.io/Lists#Map), as currently stated, affirms that all parameterised types are covariant it their parameters:

> Any type that is parameterised on another type, such as lists, has a corresponding map, which accepts a function and returns a function from the type parameterised on the domain of the function to the type parameterised on the range of the function. Further, a type that is parameterised on n types will have a map that is parameterised on n functions.

Since that is not true in general, it may be the case to modify this passage. A lightweight solution could be converting "Any type" to "Many types" and adapting the rest of the sentence accordingly.

**Comment by wadler** [comment]
Good point. Thank you! I have made the suggested change as a pull request.

How can I get access to the Agda Zulip?

**Comment by lorenzo-lipparini** [comment]
Thank you for the timely response @wadler!

You can use the following link to [sign up for the Agda Zulip](https://agda.zulipchat.com/register/).
