### ISSUE TITLE
part1/Lists: exercise requires implicit function extentionality, which has not been mentioned

### ISSUE THREAD

**Issue by lorenzo-lipparini** [plfa/plfa.github.io#586]
There is an [exercise in chapter part1/Lists](https://plfa.github.io/Lists/#exercise-all--practice) which appears to be unsolvable without a principle of extensionality for implicit functions, as in the following example:
```agda
open import Axiom.Extensionality.Propositional using (implicit-extensionality)
open import plfa.part1.Isomorphism using (extensionality; ∀-extensionality)

All-∀ : ∀ {A} {P : A → Set} xs → All P xs ≃ ∀ {x} → x ∈ xs → P x
_≃_.to (All-∀ []) All-P-xs ()
_≃_.to (All-∀ {_} {P} (x ∷ xs)) (P-x ∷ All-P-xs) (here y≡x) = subst P (sym y≡x) P-x
_≃_.to (All-∀ (x ∷ xs)) (P-x ∷ All-P-xs) (there y∈xs) = _≃_.to (All-∀ xs) All-P-xs y∈xs
_≃_.from (All-∀ []) y∈xs→P-y = []
_≃_.from (All-∀ (x ∷ xs)) y∈xs→P-y = (y∈xs→P-y (here refl)) ∷ _≃_.from (All-∀ xs) (y∈xs→P-y ∘ there)
_≃_.from∘to (All-∀ []) [] = refl
_≃_.from∘to (All-∀ (x ∷ xs)) (P-x ∷ All-P-xs) = cong (P-x ∷_) (_≃_.from∘to (All-∀ xs) All-P-xs)
_≃_.to∘from (All-∀ []) y∈xs→P-y = implicit-extensionality ∀-extensionality (λ {_} → extensionality λ ())
_≃_.to∘from (All-∀ (x ∷ xs)) y∈xs→P-y = implicit-extensionality ∀-extensionality (λ {_} → extensionality λ{ (here refl) → refl ; (there y∈xs) → cong-app (cong-app-impl (_≃_.to∘from (All-∀ xs) (y∈xs→P-y ∘ there)) _) y∈xs })
  where
  cong-app-impl : ∀ {A : Set} {B : A → Set} {f g : ∀ {x} → B x} → _≡_ {_} {∀ {x} → B x} f g → (x : A) → f {x} ≡ g {x}
  cong-app-impl refl _ = refl
```

In the book it is usually mentioned when an exercise requires extentionality, and it could be appropriate to do the same here, especially because it seems that implicit function extentionality has never been mentioned in the book (not in [chapter part1/Isomorphism section extensionality](https://plfa.github.io/Isomorphism/#extensionality), at least).

I think there are three main ways to resolve this issue:
1) Mentioning that implicit function extensionality is needed to solve the exercise, and possibly extending the section about extensionality in the Isomorphism chapter with a derivation of it;
2) Changing the goal type from `All P xs ≃ ∀ {x} → x ∈ xs → P x` to `All P xs ≃ ∀ x → x ∈ xs → P x`, so that `∀-extensionality` is enough;
3) Leaving the exercise as it is (in case the principle was deliberately left unmentioned, to increase the challenge).

**Comment by lorenzo-lipparini** [comment]
To expand on the possibility of extending the Isomorphism chapter, the proof that explicit function extensionality implies the implicit version is actually quite compact, but it does rely on the η-rule for functions (which I'm not sure was explicitly mentioned in the book). Also, the fact that Agda eagerly substitues implicit parameters means that the version of the proof with equational reasoning becomes quite cluttered:
```agda
explicit-to-implicit : ∀ {A : Set} {B : A → Set} → (∀ x → B x) → ∀ {x} → B x
explicit-to-implicit f {x} = f x

-- Compact version:
implicit-extensionality : ∀ {A : Set} {B : A → Set} → {f g : ∀ {x} → B x} → (∀ {x} → f {x} ≡ g {x}) → _≡_ {_} {∀ {x} → B x} f g
implicit-extensionality f-x≡g-x = cong explicit-to-implicit (∀-extensionality (λ x → f-x≡g-x {x}))

{-
-- What I'd like to write:
implicit-extensionality′ : ∀ {A : Set} {B : A → Set} → {f g : ∀ {x} → B x} → (∀ {x} → f {x} ≡ g {x}) → f ≡ g
implicit-extensionality′ {_} {_} {f} {g} f-x≡g-x =
  -- The outermost term must always be η-expanded, or else Agda will
  -- eagerly resolve the implicit argument
  begin
    f
  ≡⟨⟩
    (λ {x} → f {x})
  ≡⟨⟩
    explicit-to-implicit (λ x → f {x})
  ≡⟨ cong explicit-to-implicit (∀-extensionality (λ x → f-x≡g-x {x})) ⟩
    explicit-to-implicit (λ x → g {x})
  ≡⟨⟩
    (λ {x} → g {x})
  ≡⟨⟩
    g
  ∎
-}

-- What I have to write:
implicit-extensionality′ : ∀ {A : Set} {B : A → Set} → {f g : ∀ {x} → B x} → (∀ {x} → f {x} ≡ g {x}) → (λ {_} → f {_}) ≡ (λ {_} → g {_})
implicit-extensionality′ {_} {_} {f} {g} f-x≡g-x =
  -- The outermost term must always be η-expanded, or else Agda will
  -- eagerly resolve the implicit argument
  begin
    (λ {_} → f {_})
  ≡⟨⟩
    (λ {_} → (λ {x} → f {x}) {_})
  ≡⟨⟩
    (λ {_} → explicit-to-implicit (λ x → f {x}) {_})
  ≡⟨ cong explicit-to-implicit (∀-extensionality (λ x → f-x≡g-x {x})) ⟩
    (λ {_} → explicit-to-implicit (λ x → g {x}) {_})
  ≡⟨⟩
    (λ {_} → (λ {x} → g {x}) {_})
  ≡⟨⟩
    (λ {_} → g {_})
  ∎
```

**Comment by wadler** [comment]
Good point. It's easy enough to prove extensionality for an implicit function, but it is an unnecessary complication to the problem. I've rewritten to make the implicit argument explicit.

**Comment by wadler** [comment]
P.S. The eta rule for functions appears in chapter Connectives.
