### ISSUE TITLE
Can't compile Data.Nat.Base on Windows

### ISSUE THREAD

**Issue by Beal8** [plfa/plfa.github.io#593]
Hello,
I'm trying to install agda and plfa on Windows. I tried to compile a file like this :

```
open import Data.Nat

ten : ℕ
ten = 10
```
I run `agda -v 2 myfile.agda` and get this error :
`[Data.Nat.Base._+C:\Users\USERNAME\agda\plfa\standard-library\src\Data\Nat\Base.agda:74,1-76,26
<stdout>: commitBuffer: invalid argument (invalid character)`

Does anyone see how to fix this ?

**Comment by Beal8** [comment]
I restarted the terminal everything's fine now. Sorry for the issue opening

**Comment by wenkokke** [comment]
If you do ever figure out what happened, please let us know! It looks like some sort of unicode error?
