### ISSUE TITLE
part2/Properties: mention that Canonical N ⦂ A ≃ Value N × ∅ ⊢ N ⦂ A

### ISSUE THREAD

**Issue by lorenzo-lipparini** [plfa/plfa.github.io#594]
[Chapter part2/Properties introduces canonical forms](https://plfa.github.io/Properties/#canonical-forms); it is immediately mentioned how those represent well-typed closed values, with a proof of the equivalence split up into three distinct functions.

It turns out that this correspondence can be extended to an isomorphism: `Canonical N ⦂ A ≃ Value N × ∅ ⊢ N ⦂ A`.
Since the book points out isomorphisms between types very often, it seems a bit strange that it doesn't do that in this case, and I think this might lead the reader to suspect that the two concepts are not completely interchangeable.

I wonder if it would be a good idea to mention the isomorphism explicitly in the book, possibly with an exercise that asks the reader to prove it (maybe reusing the `canonical`, `typed` and `value` functions).

**Comment by lorenzo-lipparini** [comment]
Another doubt I have which is tangentially related is about the use of the `canonical` function in the proof of [progress](https://plfa.github.io/Properties#progress): is there a particular reason to use that function, given that pattern matching on the `Value` returned by the recursive call to `progress` would be enough, and actually spare a nested with abstraction?

The code without using `canonical` would look like this:

```agda
progress : ∀ {M A} → ∅ ⊢ M ⦂ A → Progress M
progress (⊢ƛ _) = done V-ƛ
progress (⊢L · ⊢M) with progress ⊢L
... | step L—→L′ = step (ξ-·₁ L—→L′)
... | done V-ƛ with progress ⊢M
...   | step M—→M′ = step (ξ-·₂ V-ƛ M—→M′)
...   | done V-M = step (β-ƛ V-M)
progress ⊢zero = done V-zero
progress (⊢suc ⊢M) with progress ⊢M
... | step M—→M′ = step (ξ-suc M—→M′)
... | done V-M = done (V-suc V-M)
progress (⊢case ⊢L ⊢M ⊢N) with progress ⊢L
... | step L—→L′ = step (ξ-case L—→L′)
... | done V-zero = step β-zero
... | done (V-suc V-M) = step (β-suc V-M)
progress (⊢μ ⊢M) = step β-μ
```

**Comment by wadler** [comment]
Nice observation regarding the isomorphism. Please prove it and enter the answer into the answers repository, then edit the chapter accordingly with proof of the isomorphism added as an exercise. (I'd be reluctant to state it is an isomorphism unless someone actually proved it.)

Regarding progress, did you run that code? When I omit the call to canonical from the code in the book it yields a type error.

**Comment by lorenzo-lipparini** [comment]
Thanks for the response @wadler.

About the isomorphism, I'd be happy to contribute with a solution, but I still don't have access answers repository, and neither do I know where to ask for it 😅.

Regarding progress, I did type-check the code on my setup; one thing to note is that I didn't just omit the call to the `canonical` lemma, but I also explicitly pattern matched on the evidence that some terms are `Value`s, which the implementation in the book doesn't do:
```agda
-- Line from the code above:
... | done V-ƛ with progress ⊢M
-- Corresponding line on the book:
... | done VL with progress ⊢M

-- Lines from the code above:
... | done V-zero = step β-zero
... | done (V-suc V-M) = step (β-suc V-M)
-- Corresponding lines in the book:
... | done VL with canonical ⊢L VL
...   | C-zero =  step β-zero
...   | C-suc CL = step (β-suc (value CL))
```
This is consistent with the fact that `Canonical N ⦂ A` contains the same information as `Value N` and `∅ ⊢ N ⦂ A`: pattern matching on the parameters of the latter types should have the same effect, without having to construct (redundant) evidence for `Canonical N ⦂ A`.

With that being said, I discovered just yesterday that my version of Agda is a little more recent than the one suggested for the book, which is also a possible explanation for the problem.

**Comment by lorenzo-lipparini** [comment]
@wadler I am now running Agda version 2.6.1.3, which is the one suggested for the book, and the implementation of `progress` from above still type-checks.

**Comment by wadler** [comment]
Cool! You are absolutely right. I thought canonical forms was essential, but it is not. I have simplified the proof along the lines you suggest, deleted the section on canonical forms, and added an exercise that defines canonical forms and asks the reader to show that being a canonical form is isomorphic to being well-typed and a value.

I've also invited you to plfa-answers. Thank you!

**Comment by lorenzo-lipparini** [comment]
Thanks @wenkokke for reopening the issue, and thanks @wadler for your response. I'll be happy to submit a solution to the new exercise later this week.

@wadler I am happy with all the changes you have implemented, but I'm worried that a little problem may have gone unnoticed: canonical forms and the proof of `progress` happen to be mentioned in the next chapter of book (possibly even in later ones?), and those references should probably be updated.
Consider, for example, the following paragraph from the [chapter DeBruijn, section progress](https://plfa.github.io/DeBruijn/#progress):
> The statement and proof of progress is much as before, appropriately annotated. We no longer need to explicitly refer to the Canonical Forms lemma, since it is built-in to the definition of value:

As another example, the line count in [section intrinsic typing is golden](https://plfa.github.io/DeBruijn/#intrinsic-typing-is-golden) may need to be updated.

**Comment by wenkokke** [comment]
Ah, yes, that should perhaps be automagically generated.
