### ISSUE TITLE
Induction: no import of _^_ and "Your code goes here" resp. exercise

### ISSUE THREAD

**Issue by ulysses4ever** [plfa/plfa.github.io#611]
There is an exercise about exponentiation but if I attempt it, I see that `_^_` is not known. This can be fixed by adding the operator to the import statement:

https://github.com/plfa/plfa.github.io/blob/f5b25b9c847abdd7dd901aa383adc06515a1c6de/src/plfa/part1/Induction.lagda.md?plain=1#L32

I understand that it's an oversight, not a lesson in teaching imports? Because the text doesn't say a word about this challenge and the previous exercise is about monus, which is imported.

Also, the exercise misses the usual `-- Your code goes here` snippet, while its neighbors have the snippet.

**Comment by wadler** [comment]
Regarding import, "A word on the exercises" states "You may need to import library functions required for the solution."

Regarding the missing "-- Your code goes here", please file a pull request.

**Comment by ulysses4ever** [comment]
@wadler thanks! here's the pr:  #612.
