### ISSUE TITLE
Induction: can't import Naturals.Bin/from/to due to builtin pragmas there

### ISSUE THREAD

**Issue by ulysses4ever** [plfa/plfa.github.io#613]
I approach the Bin-laws exercise in `Induction.lagda.md`, and for that I need definitions from `Naturals.lagda.md`. I add

```agda
open import plfa.part1.Naturals using (Bin; to; from)
```

to the end of the imports list of `Induction.lagda.md` and, surprisingly, get the error:

```shell
Duplicate binding for built-in thing NATMINUS, previous binding to
Agda.Builtin.Nat._-_
when scope checking the declaration
  open import plfa.part1.Naturals using (Bin; to; from)
```

My understanding of the problem is that the `builtin` pragmas in Naturals don't respect module boundaries. How am I supposed to fix it? One way is to eliminate all imports of `Data.Nats` and replace them with imports from `Naturals`. Is it what was meant by the authors? Seems strange to undo imports that are provided in the book.

**Comment by wadler** [comment]
Another way to deal with it is to copy the definitions of Bin, to, from in Naturals to Induction.

**Comment by ulysses4ever** [comment]
But copying code is considered bad, isn't it? Maybe it'd be better to replace the imports from Data Nats in the book, so people don't stubble upon it in the future?
