### ISSUE TITLE
Build fail with icu4c on Mac M1

### ISSUE THREAD

**Issue by conal** [plfa/plfa.github.io#633]
I am trying and failing to build PLFA from an up-to-date local repo clone on my MacBook Pro with M1 running MacOS Monterey (12.2.1) and using Homebrew for various utilities. Is this configuration expected to work?

The build derails at the `icu4c` library (installed via Homebrew), which I think is used in the text-icu Haskell library. The error messages suggest inconsistent expectations about x86 vs arm64. For instance, “`ld: warning: directory not found for option '-L/usr/local/opt/icu4c/lib'`”. That location is where `icu4c` *would be* installed on an x86 Mac. A similarly fishy error message immediately follows:

    ld: warning: ignoring file /opt/homebrew/Cellar/icu4c/70.1/lib//libicuuc.dylib,
    building for macOS-x86_64 but attempting to link with file built for macOS-arm64

And another hint of x86-vs-arm confusion:

    --  While building package plfa-20.10 (scroll up to its section to see the error) using:
          /Users/conal/.stack/setup-exe-cache/x86_64-osx/Cabal-simple_mPHDZzAJ_3.2.1.0_ghc-8.10.5 \
             --builddir=.stack-work/dist/x86_64-osx/Cabal-3.2.1.0 build lib:plfa exe:site \
             exe:update-contributors --ghc-options " 

More details below.

Any help appreciated!

    bash-3.2$ make
    /Library/Developer/CommandLineTools/usr/bin/make build
    stack build --only-dependencies
    Building website
    stack build
    Building all executables for `plfa' once. After a successful build of all of them, only specified executables will be rebuilt.
    plfa> configure (lib + exe)
    Configuring plfa-20.10...
    plfa> build (lib + exe)
    Preprocessing executable 'update-contributors' for plfa-20.10..
    Building executable 'update-contributors' for plfa-20.10..
    Preprocessing library for plfa-20.10..
    Building library for plfa-20.10..
    [1 of 7] Compiling Hakyll.Web.Agda
    [2 of 7] Compiling Hakyll.Web.Routes.Permalink
    [3 of 7] Compiling Hakyll.Web.Sass
    [4 of 7] Compiling Hakyll.Web.Template.Context.Derived
    [5 of 7] Compiling Hakyll.Web.Template.Context.Metadata
    [6 of 7] Compiling Hakyll.Web.Template.Context.Title
    [7 of 7] Compiling Hakyll.Web.Template.Numeric
    ld: warning: directory not found for option '-L/usr/local/opt/icu4c/lib'
    ld: warning: ignoring file /opt/homebrew/Cellar/icu4c/70.1/lib//libicuuc.dylib, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
    ld: warning: ignoring file /opt/homebrew/Cellar/icu4c/70.1/lib//libicui18n.dylib, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
    ld: warning: ignoring file /opt/homebrew/Cellar/icu4c/70.1/lib//libicudata.dylib, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
    Preprocessing executable 'site' for plfa-20.10..
    Building executable 'site' for plfa-20.10..
    [1 of 1] Compiling Main
    Linking .stack-work/dist/x86_64-osx/Cabal-3.2.1.0/build/site/site ...
    ld: warning: directory not found for option '-L/usr/local/opt/icu4c/lib'
    ld: warning: ignoring file /opt/homebrew/Cellar/icu4c/70.1/lib//libicuuc.dylib, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
    ld: warning: ignoring file /opt/homebrew/Cellar/icu4c/70.1/lib//libicui18n.dylib, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
    ld: warning: ignoring file /opt/homebrew/Cellar/icu4c/70.1/lib//libicudata.dylib, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
    Undefined symbols for architecture x86_64:
      "_uregex_end_70", referenced from:
          ___hs_uregex_end in libHStext-icu-0.7.1.0-4lRD4kS3GycDn8oAzrlddC.a(text_icu.o)
      "_uregex_start_70", referenced from:
          ___hs_uregex_start in libHStext-icu-0.7.1.0-4lRD4kS3GycDn8oAzrlddC.a(text_icu.o)
      "_uregex_setText_70", referenced from:
          ___hs_uregex_setText in libHStext-icu-0.7.1.0-4lRD4kS3GycDn8oAzrlddC.a(text_icu.o)
      "_uregex_clone_70", referenced from:
          ___hs_uregex_clone in libHStext-icu-0.7.1.0-4lRD4kS3GycDn8oAzrlddC.a(text_icu.o)
      "_uregex_groupCount_70", referenced from:
          ___hs_uregex_groupCount in libHStext-icu-0.7.1.0-4lRD4kS3GycDn8oAzrlddC.a(text_icu.o)
      "_uregex_find_70", referenced from:
          ___hs_uregex_find in libHStext-icu-0.7.1.0-4lRD4kS3GycDn8oAzrlddC.a(text_icu.o)
      "_uregex_open_70", referenced from:
          ___hs_uregex_open in libHStext-icu-0.7.1.0-4lRD4kS3GycDn8oAzrlddC.a(text_icu.o)
      "_uregex_close_70", referenced from:
          ___hs_uregex_close in libHStext-icu-0.7.1.0-4lRD4kS3GycDn8oAzrlddC.a(text_icu.o)
      "_uregex_setStackLimit_70", referenced from:
          ___hs_uregex_setStackLimit in libHStext-icu-0.7.1.0-4lRD4kS3GycDn8oAzrlddC.a(text_icu.o)
      "_uregex_setTimeLimit_70", referenced from:
          ___hs_uregex_setTimeLimit in libHStext-icu-0.7.1.0-4lRD4kS3GycDn8oAzrlddC.a(text_icu.o)
      "_u_errorName_70", referenced from:
          ___hs_u_errorName in libHStext-icu-0.7.1.0-4lRD4kS3GycDn8oAzrlddC.a(text_icu.o)
    ld: symbol(s) not found for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    `gcc' failed in phase `Linker'. (Exit code: 1)

    --  While building package plfa-20.10 (scroll up to its section to see the error) using:
          /Users/conal/.stack/setup-exe-cache/x86_64-osx/Cabal-simple_mPHDZzAJ_3.2.1.0_ghc-8.10.5 --builddir=.stack-work/dist/x86_64-osx/Cabal-3.2.1.0 build lib:plfa exe:site exe:update-contributors --ghc-options " -fdiagnostics-color=always"

**Comment by wenkokke** [comment]
Does Agda compile on M1? ICU4C is an Agda dependency as well, so if that compiles, just replace the `text-icu` dependency with whatever more recent version Agda uses.

**Comment by wenkokke** [comment]
It looks like they have moved onto version 0.8.

**Comment by conal** [comment]
> Does Agda compile on M1?

Yes, Agda compiles fine on my M1.

**Comment by conal** [comment]
I uninstalled arm64 Homebrew and installed from scratch. No help. I made a second Homebrew installation for x86 emulation, installed `icu4c` there, and tried building PLFA again (with and without prefixing `make` with `arch -x86_64`). Still stuck.

**Comment by wenkokke** [comment]
Could you try forcing the text-icu version to >=0.8?

**Comment by conal** [comment]
I get the same results when I replace
```
text-regex-replace-0.1.1.3@sha256:e7f612df671c93ced54a3d26528db37852069884e5cb67d5afbb49d3defb5eb9,1627
```

by

```agda
- text-icu-0.8.0
```

in `stack.yaml`:
```
bash-3.2$ make
/Library/Developer/CommandLineTools/usr/bin/make build
stack build --only-dependencies
WARNING: Ignoring plfa's bounds on text-icu (>=0.7.1 && <0.8); using text-icu-0.8.0.
Reason: allow-newer enabled.
Building website
stack build
WARNING: Ignoring plfa's bounds on text-icu (>=0.7.1 && <0.8); using text-icu-0.8.0.
Reason: allow-newer enabled.
Building all executables for `plfa' once. After a successful build of all of them, only specified executables will be rebuilt.
plfa> configure (lib + exe)
Configuring plfa-20.10...
plfa> build (lib + exe)
Preprocessing library for plfa-20.10..
Building library for plfa-20.10..
[1 of 7] Compiling Hakyll.Web.Agda
[2 of 7] Compiling Hakyll.Web.Routes.Permalink
[3 of 7] Compiling Hakyll.Web.Sass
[4 of 7] Compiling Hakyll.Web.Template.Context.Derived
[5 of 7] Compiling Hakyll.Web.Template.Context.Metadata
[6 of 7] Compiling Hakyll.Web.Template.Context.Title
[7 of 7] Compiling Hakyll.Web.Template.Numeric
ld: warning: directory not found for option '-L/usr/local/opt/icu4c/lib'
ld: warning: ignoring file /opt/homebrew/opt/icu4c/lib/libicuuc.dylib, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /opt/homebrew/opt/icu4c/lib/libicudata.dylib, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /opt/homebrew/opt/icu4c/lib/libicui18n.dylib, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
Preprocessing executable 'site' for plfa-20.10..
Building executable 'site' for plfa-20.10..
[1 of 1] Compiling Main [Hakyll.Web.Sass changed]
Linking .stack-work/dist/x86_64-osx/Cabal-3.2.1.0/build/site/site ...
ld: warning: directory not found for option '-L/usr/local/opt/icu4c/lib'
ld: warning: ignoring file /opt/homebrew/opt/icu4c/lib/libicuuc.dylib, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /opt/homebrew/opt/icu4c/lib/libicui18n.dylib, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /opt/homebrew/opt/icu4c/lib/libicudata.dylib, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
Undefined symbols for architecture x86_64:
  "_utext_openUChars_70", referenced from:
      ___hs_utext_openUChars in libHStext-icu-0.8.0-6DJy5nEKT5u32jtLf23fP1.a(text_icu.o)
  "_uregex_clone_70", referenced from:
      ___hs_uregex_clone in libHStext-icu-0.8.0-6DJy5nEKT5u32jtLf23fP1.a(text_icu.o)
  "_uregex_end_70", referenced from:
      ___hs_uregex_end in libHStext-icu-0.8.0-6DJy5nEKT5u32jtLf23fP1.a(text_icu.o)
  "_uregex_start_70", referenced from:
      ___hs_uregex_start in libHStext-icu-0.8.0-6DJy5nEKT5u32jtLf23fP1.a(text_icu.o)
  "_uregex_setUText_70", referenced from:
      ___hs_uregex_setUText in libHStext-icu-0.8.0-6DJy5nEKT5u32jtLf23fP1.a(text_icu.o)
  "_utext_close_70", referenced from:
      ___hs_utext_close in libHStext-icu-0.8.0-6DJy5nEKT5u32jtLf23fP1.a(text_icu.o)
  "_uregex_groupCount_70", referenced from:
      ___hs_uregex_groupCount in libHStext-icu-0.8.0-6DJy5nEKT5u32jtLf23fP1.a(text_icu.o)
  "_uregex_find_70", referenced from:
      ___hs_uregex_find in libHStext-icu-0.8.0-6DJy5nEKT5u32jtLf23fP1.a(text_icu.o)
  "_uregex_open_70", referenced from:
      ___hs_uregex_open in libHStext-icu-0.8.0-6DJy5nEKT5u32jtLf23fP1.a(text_icu.o)
  "_u_errorName_70", referenced from:
      ___hs_u_errorName in libHStext-icu-0.8.0-6DJy5nEKT5u32jtLf23fP1.a(text_icu.o)
  "_uregex_setTimeLimit_70", referenced from:
      ___hs_uregex_setTimeLimit in libHStext-icu-0.8.0-6DJy5nEKT5u32jtLf23fP1.a(text_icu.o)
  "_uregex_close_70", referenced from:
      ___hs_uregex_close in libHStext-icu-0.8.0-6DJy5nEKT5u32jtLf23fP1.a(text_icu.o)
  "_uregex_setStackLimit_70", referenced from:
      ___hs_uregex_setStackLimit in libHStext-icu-0.8.0-6DJy5nEKT5u32jtLf23fP1.a(text_icu.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`gcc' failed in phase `Linker'. (Exit code: 1)

--  While building package plfa-20.10 (scroll up to its section to see the error) using:
      /Users/conal/.stack/setup-exe-cache/x86_64-osx/Cabal-simple_mPHDZzAJ_3.2.1.0_ghc-8.10.5 --builddir=.stack-work/dist/x86_64-osx/Cabal-3.2.1.0 build lib:plfa exe:site exe:update-contributors --ghc-options ""
    Process exited with code: ExitFailure 1
```

**Comment by wenkokke** [comment]
Might be a problem with text-regex-replace, then, which I think Agda doesn’t use…

**Comment by wenkokke** [comment]
I am in the process of writing this library out of the build process but I’m not done yet and have been out of the running for a while…

**Comment by wenkokke** [comment]
Wait, @conal, did you tell Cabal about the location of icu4c? For example, by putting the following in your `cabal.project.local` or passing them as flags?
```
extra-include-dirs: /usr/local/opt/icu4c/include
extra-lib-dirs: /usr/local/opt/icu4c/lib
```
I don’t have an M1, so I can’t test this for myself.

This could be fixed by replacing the uses of text-icu and text-icu-replace with a different, pure Haskell regular expression library.

**Comment by wenkokke** [comment]
@conal I’ve removed all C dependencies, including text-icu and text-icu-replace, so you shouldn’t have any further problems building the book locally.

I’m still writing instructions for contributors, but you need at least node and npm installed for `make build` to work. Other make commands might have other dependencies, which you can find in the Makefile for now.

**Comment by conal** [comment]
> Wait, @conal, did you tell Cabal about the location of icu4c?

I did not. Thanks.

**Comment by conal** [comment]
Thanks also for simplifying the build process (by removing C dependencies) and adding contributor instructions!
