### ISSUE TITLE
Any plan to upgrade Agda?

### ISSUE THREAD

**Issue by lengyijun** [plfa/plfa.github.io#634]
If a pr of Agda 2.6.2.1 is welcome ?

**Comment by wadler** [comment]
We are a little slower than usual at updating, because Wen currently has difficulty using a keyboard. But I am sure we will update at some point, so such a pr would be extremely helpful. Thank you for the offer!

**Comment by wenkokke** [comment]
I am currently away with carpal tunnel, but I have a branch on which I’ve been working to port the code over to 2.6.2. The main problem is that Agda broke their library API moving to this version.

**Comment by wenkokke** [comment]
You are free to submit for requests to the ~~shake~~ shoggoth branch, as I am planning to merge this once it’s building correctly.

**Comment by wenkokke** [comment]
Fixed in HEAD
