### ISSUE TITLE
standard-library version: 1.3 or 1.6 ?

### ISSUE THREAD

**Issue by lengyijun** [plfa/plfa.github.io#635]
In Readme :
`git clone https://github.com/agda/agda-stdlib.git --branch v1.6 --depth 1 agda-stdlib  `

But if we use 
` git clone --depth 1 --recurse-submodules --shallow-submodules https://github.com/plfa/plfa.github.io plfa`
It will switch to 1.3.

**Comment by wadler** [comment]
Thanks. Wen will need to comment, it may take her a while to get around to it.

**Comment by wenkokke** [comment]
I believe it should be 1.6, but if either works, that should be fine as well.

We're planning to upgrade shortly either way, and this'll be fixed in the process.

**Comment by wenkokke** [comment]
Will be fixed by #668
