### ISSUE TITLE
Commendation on source linking

### ISSUE THREAD

**Issue by GetContented** [plfa/plfa.github.io#641]
I realise this is not a normalised way to applaud anything, but given github don't have such affordances, I'll use this issue tracker to do such.

I really appreciate that the `source` is directly linked on every page. This invitation for the public to support and aide in the development process is sorely lacking in most projects. Well done!

Feel free to close this issue once you've given yourselves a well deserved pat on the back.

More stuff like this, please! ❤️

**Comment by wadler** [comment]
It's a pleasure to receive compliments such as this one. Thank you! Pat yourself on the back for taking the time to give a compliment---people do so too rarely.
