### ISSUE TITLE
Beginning (checking exercises)

### ISSUE THREAD

**Issue by GetContented** [plfa/plfa.github.io#642]
Perhaps I've missed it, but at the very beginning it would be useful to have an explanation of how one should get agda to check one's work as one goes.

Below is what I tried, which seems tedious (because it takes a while to compile - but it seems perhaps this is only the first time). In the place of having something faster, it will do.

So, the first exercise is "seven" whereby one describes a definition for seven using the constructors of ℕ. To compile the answer, I needed to do this:

`> agda -v 2 plfa/part1/Naturals.lagda.md`

So, given this is the first time we're interacting with Agda, perhaps a little more guidance, or a link to a relevant explanation in the getting started section might be useful?

It also seems necessary to write it as a definition: ie to write `seven =` in front of the required answer, or it won't compile, at which point I get the error `Missing type signature for left hand side`. That's not obvious from the instruction above it, or the error, given what little amount of Agda one knows at this point.

I'm also not sure if it's being suggested that we should also write a type sig nature for it, but it doesn't seem to matter if I do or not to whether it can compile, so I assume not.

**Comment by wadler** [comment]
Good point. I've added the following text to the exercise. Will that do?

You will need to give both a type signature and definition for the
variable `seven`. Type `C-c C-l` in Emacs to instruct Agda to re-load.

**Comment by GetContented** [comment]
> Good point. I've added the following text to the exercise. Will that do?

Yeah, I think that's excellent. Thanks.
