### ISSUE TITLE
Confusing paragraph at beginning of Naturals (teaching via examples)

### ISSUE THREAD

**Issue by GetContented** [plfa/plfa.github.io#643]
Context: In the beginning section on the Naturals where we "unpack the inference rules" at  https://github.com/plfa/plfa.github.io/blob/dev/src/plfa/part1/Naturals.lagda.md#unpacking-the-inference-rules at version on the date of this issue, with sha https://github.com/plfa/plfa.github.io/commit/45d74c7af42e90fc7fd68c8a414b699d6f32c763

The section reads as follows:

> Let's unpack the inference rules. Each inference rule consists of zero or more judgments written above a horizontal line, called the hypotheses, and a single judgment written below, called the conclusion. The first rule is the base case. It has no hypotheses, and the conclusion asserts that zero is a natural. The second rule is the inductive case. It has one hypothesis, which assumes that m is a natural, and the conclusion asserts that suc m is also a natural.

The trouble here is that we're attempting to explain & understand two things at once:

1. the general structure of inference rules
2. the particular set of inference rules for ℕ

As we all know, humans best understand abstractions from concretions, unless we're mapping from abstractions we already understand. This means we best understand by triangulating to an abstraction from _at least_ 3 examples. Yet here we're attempting to explain a single concretion _with_ its abstraction.

It would seem it might be best to explain these things separately. Perhaps to show 2 more examples of simple "inference rules" that allow the reader to trigulate the syntax of the file without explanation (ie "show don't tell"). I realise how difficult this is.

Aside from that, the first part could be rewritten for clarity:

```
Let's unpack the inference rules. They consist of some lines above and below a horizontal line. Above the horizontal line are zero or more judgment lines, collectively called the hypotheses. Below the horizontal line is a single judgment line, called the conclusion.
```

One immediately wonders what happens when one doesn't follow this suggested syntax, and also what the inference rules are "for". At the present moment, the reader is suspending their understanding: waiting for some context to plug the meaning of "inference rules" into. It'd possibly be kinder on the reader to give them a map of what this stuff is for upfront, though that depends if the reader is primarily a top-down or bottom-up learner, to a degree. It's not terribly important, really. Most readers simply suspend their understanding until later in this case. 👍 

(BTW I really appreciate that this book exists, to frame the suggestions I'm making here — it comes from a place of gratitude and hoping to help improve, not a place of negativity.)

**Comment by wadler** [comment]
Thanks for the suggestion. While often it helps to have more examples, sometimes it is a distraction. Here I think it is better to develop the one example (Naturals, plus, time) in sequence, rather than to delay at this point to include more examples.

**Comment by GetContented** [comment]
Ok. Maybe a better way fo me to say this might have been that it's not clear what inference rules are, what their syntax is, or what they're for. (It doesn't seem to be something for the computer at the point where they're introduced, and it's unclear why the reader should care about them).

At this point in the text, I'm just putting inference rules on the shelf and waiting to see what the text does with them (I haven't read much further because I've been waiting until I learned a bit more emacs because vcode just wasn't cutting it).
