### ISSUE TITLE
agda-mode compile not working (macOS 11.6.5)

### ISSUE THREAD

**Issue by GetContented** [plfa/plfa.github.io#644]
I was using VScode but the plugin didn't seem to let me do case splitting, so I thought I'd switch to native emacs, or aquamacs. I ran `agda-mode setup` just fine, but `agda-mode compile` didn't work so well:

```
In toplevel form:
~/code/agda/agda/.stack-work/install/x86_64-osx/2ea356db11ab153a6ba147b7da51aa71a671fd44c574cb318e18fbe51bafd587/8.8.3/share/x86_64-osx-ghc-8.8.3/Agda-2.6.1.3/emacs-mode/annotation.el:6:1:Error: Package cl is deprecated

In toplevel form:
~/code/agda/agda/.stack-work/install/x86_64-osx/2ea356db11ab153a6ba147b7da51aa71a671fd44c574cb318e18fbe51bafd587/8.8.3/share/x86_64-osx-ghc-8.8.3/Agda-2.6.1.3/emacs-mode/eri.el:7:1:Error: Package cl is deprecated

In toplevel form:
~/code/agda/agda/.stack-work/install/x86_64-osx/2ea356db11ab153a6ba147b7da51aa71a671fd44c574cb318e18fbe51bafd587/8.8.3/share/x86_64-osx-ghc-8.8.3/Agda-2.6.1.3/emacs-mode/agda-input.el:22:1:Error: Package cl is deprecated

In toplevel form:
~/code/agda/agda/.stack-work/install/x86_64-osx/2ea356db11ab153a6ba147b7da51aa71a671fd44c574cb318e18fbe51bafd587/8.8.3/share/x86_64-osx-ghc-8.8.3/Agda-2.6.1.3/emacs-mode/agda2-highlight.el:11:1:Error: Package cl is deprecated

In toplevel form:
~/code/agda/agda/.stack-work/install/x86_64-osx/2ea356db11ab153a6ba147b7da51aa71a671fd44c574cb318e18fbe51bafd587/8.8.3/share/x86_64-osx-ghc-8.8.3/Agda-2.6.1.3/emacs-mode/agda2-mode.el:17:1:Error: Package cl is deprecated
Unable to compile the following Emacs Lisp files:
  /Users/getcontented/code/agda/agda/.stack-work/install/x86_64-osx/2ea356db11ab153a6ba147b7da51aa71a671fd44c574cb318e18fbe51bafd587/8.8.3/share/x86_64-osx-ghc-8.8.3/Agda-2.6.1.3/emacs-mode/annotation.el
  /Users/getcontented/code/agda/agda/.stack-work/install/x86_64-osx/2ea356db11ab153a6ba147b7da51aa71a671fd44c574cb318e18fbe51bafd587/8.8.3/share/x86_64-osx-ghc-8.8.3/Agda-2.6.1.3/emacs-mode/eri.el
  /Users/getcontented/code/agda/agda/.stack-work/install/x86_64-osx/2ea356db11ab153a6ba147b7da51aa71a671fd44c574cb318e18fbe51bafd587/8.8.3/share/x86_64-osx-ghc-8.8.3/Agda-2.6.1.3/emacs-mode/agda-input.el
  /Users/getcontented/code/agda/agda/.stack-work/install/x86_64-osx/2ea356db11ab153a6ba147b7da51aa71a671fd44c574cb318e18fbe51bafd587/8.8.3/share/x86_64-osx-ghc-8.8.3/Agda-2.6.1.3/emacs-mode/agda2-highlight.el
  /Users/getcontented/code/agda/agda/.stack-work/install/x86_64-osx/2ea356db11ab153a6ba147b7da51aa71a671fd44c574cb318e18fbe51bafd587/8.8.3/share/x86_64-osx-ghc-8.8.3/Agda-2.6.1.3/emacs-mode/agda2-mode.el
```

**Comment by wenkokke** [comment]
It might be best to report this at [agda/agda](https://github.com/agda/agda/issues), rather than here?

**Comment by GetContented** [comment]
> It might be best to report this at [agda/agda](https://github.com/agda/agda/issues), rather than here?

Ok, will do. As a complete noob with Emacs, I didn't realise it was part of Agda and not part of this course.

**Comment by andreasabel** [comment]
This is reported against Agda 2.6.1.3, but I have reasons to suspect this is fixed by Agda 2.6.2.

**Comment by GetContented** [comment]
As @andreasabel suggests, it's reported against 2.6.1.3, but that's because the book recommends we lock to that version. I'll try using the later version, but I guess I'm a little worried the book won't be appropriate to that version anymore. :(

**Comment by andreasabel** [comment]
@GetContented Please let us know how it goes!

**Comment by wenkokke** [comment]
The book won’t yet compile with 2.6.2, unfortunately. There was a major breaking change between 2.6.1.x and 2.6.2 which we’ve not yet adapted to.

**Comment by GetContented** [comment]
It does solve the issue @andreasabel — I can now load and typecheck files in the emac v27.2 that's built into my OS. Acquamacs (the editor suggested by the book) seems not to be working, though, (it's not typechecking) but that might just be my lack of familiarity with it, so the issue with agda & agda mode is sort of solved, even though as wenhokke relays, we can't use 2.6.2.

Thankfully most of the code exercises so far seem to be standalone so I can just enter them into a fresh file. Hopefully all the exercises are similarly relatively self-contained.

Thankyou all!

**Comment by andreasabel** [comment]
@wenkokke 
> The book won’t yet compile with 2.6.2, unfortunately. There was a major breaking change between 2.6.1.x and 2.6.2 which we’ve not yet adapted to.

It would be good to have an issue keeping a TODO list for migration to Agda 2.6.2.
