### ISSUE TITLE
Catch up with the Haskell ecosystem, fix CI

### ISSUE THREAD

**Issue by andreasabel** [plfa/plfa.github.io#649]
I noticed that the current CI does not work.  CI hangs at the stack build of `basement`, which is a dependency of `pandoc` that is no longer needed in the latest releases of `pandoc`, starting 2.16.  However, `pandoc-citeproc`, which is a dead end by now, requires `pandoc < 2.15`.

Maybe progress could be made by getting rid of `pandoc-citeproc`, used here: 
https://github.com/plfa/plfa.github.io/blob/a798dc6a76ced81fc3fbb869861d010423e30ccb/hs/Main.hs#L364-L374
Called e.g. here:
https://github.com/plfa/plfa.github.io/blob/a798dc6a76ced81fc3fbb869861d010423e30ccb/hs/Main.hs#L235-L237
It is claimed that `pandoc-citeproc` is obsolete, but I could not find a drop-in migration guide.  Maybe it is as simple as passing the `--citeproc` option to `pandoc-2.18`.

Maybe I can help with fixing the CI, if getting some guidance...

**Comment by wadler** [comment]
Thanks, Andreas. Wen is in charge of CI. She's had problems maintaining it because of RSI, and I expect would be glad to have assistance.

**Comment by andreasabel** [comment]
I put a draft PR at
- #652

**Comment by wenkokke** [comment]
Fixed in HEAD
