### ISSUE TITLE
Rearrangement corollary flipped association on +-assoc

### ISSUE THREAD

**Issue by GetContented** [plfa/plfa.github.io#653]
The section entitled "Our first corollary" includes the following sentence:

> Proposition +-assoc n p q shifts parentheses from right to left: (n + p) + q ≡ n + (p + q)

However, it _seems_ to be that it's the opposite. That is, it takes `(n + p) + q` which has left-assocatied parenthicization and shifts it to be right-associated parenthesization in `n + (p + q)`. I realise that mathematics has no preference as to which side to read first (assuming I've understood the ≡ operator here — as being some form of mathematical exact equality), but it seems that _Agda **does**_, and indeed it seems that we need to have it provided in a particular order, which seems to be the entire point of `sym` as far as I can tell.

I might just be misguided here, but I got a little confused about that point, so maybe the material should be slightly adjusted to address others who have similar questions, or altered if it's incorrect?

**Comment by GetContented** [comment]
> assuming I've understood the ≡ operator here — as being some form of mathematical exact equality

This brings up an interesting point I've been pondering for the last few days. This is the second chapter and we haven't had a definition yet for what ≡ means; in fact, quite a few of the operators remain unexplained. Is this becuase we would expect the curious to go on a journey to discover these items in the agda docs themselves, or we're going for an intuition-first approach here, or because this book is intended to be a supplement to a course rather than being intended for self-study in its own right? I haven't made my way through enough of the material yet to understand how to frame it.

**Comment by wadler** [comment]
Thanks. It should indeed be left-to-right, not the inverse. I've fixed the text. (Fixes aren't showing up online just now, but will soon.)

When equality and related operations are first imported in Chapter Naturals, the reader is told "We take these as givens for now, but will see how they are defined in Chapter [Equality](https://plfa.inf.ed.ac.uk/Equality/)."

**Comment by GetContented** [comment]
> Thanks. It should indeed be left-to-right, not the inverse. I've fixed the text. (Fixes aren't showing up online just now, but will soon.)

Good to know. Thanks for fixing. I'll close this issue then.


> When equality and related operations are first imported in Chapter Naturals, the reader is told "We take these as givens for now, but will see how they are defined in Chapter [Equality](https://plfa.inf.ed.ac.uk/Equality/)."

Oh excellent, thanks for the reminder. Apologies for asking again.
