### ISSUE TITLE
Some difficulty understanding second proof in induction chapter

### ISSUE THREAD

**Issue by GetContented** [plfa/plfa.github.io#654]
In the section in the induction chapter called "Our second proof: commutativity", under the first lemma, the following line appears:

> This in turn follows by prefacing suc to both sides of the induction hypothesis

Perhaps the word we want there might be **prefixing**, or **prepending** not _prefacing_. This isn't a big problem at all, it just stuck out a little.

The main piece that seemed confusing was that it reads as though the "addition of `suc` to both sides of the induction hypothesis" is illustrated after the explanatory line above, however the code is actually **preceding** this line, not what **follows** this line. This took me a minute or two to unpack.

Essentially, it's difficult to understand the line of reasoning being suggested to understand how the proof proceeds. Or, put another way, it's difficult to see how the explanation maps to the Agda code above it.

Apologies if this comes across as being too critical; the thought here was that perhaps others' confusion might be avoided in the future if we can rework it to be a little easier to understand.

**Comment by wadler** [comment]
You are very welcome to submit pull requests with improved wording. That's much more helpful (from my point of view) than being asked to rewrite a section!

**Comment by GetContented** [comment]
> You are very welcome to submit pull requests with improved wording. That's much more helpful (from my point of view) than being asked to rewrite a section!

Apologies. I'll certainly try to give it a go.
