### ISSUE TITLE
Some difficulty understanding associativity with rewrite

### ISSUE THREAD

**Issue by GetContented** [plfa/plfa.github.io#655]
In the section entitled "Associativity with rewrite", it's not easy to understand why we are allowed to simpify with the base and inductive cases somehow automatically, and how the `rewrite` (rule? function?) "knows" to do a match and replace on this transformed version.

Perhaps it's just that it's not clear what `rewrite` is "doing".

In particular, this sentence is baffling:

> After rewriting with the inductive hypothesis these two terms are equal, and the proof is again given by refl. Rewriting by a given equation is indicated by the keyword rewrite followed by a proof of that equation. Rewriting avoids not only chains of equations but also the need to invoke cong.

It feels a _little_ like we've described rewriting as... rewriting.

That is, it's not apparent how Agda knows when we tell it `+-assoc′ (suc m) n p  rewrite +-assoc′ m n p  =  refl`  that it can understand this to mean to transform this into `suc ((m + n) + p) ≡ suc (m + (n + p))`, nor how it knows how to ignore the `suc` there on each side to match the form of `+-assoc′ m n p` to transform the matched LHS pattern into the "output" RHS pattern. It's fairly possible I'm missing something obvious.

To boot, what manner of form "is" `rewrite` such that it can appear where it does, in the pattern matching position, on the left of `=`?

**Comment by wadler** [comment]
Rewrite takes the goal to be proved into another goal. For instance, the goal

    suc ((m + n) + p) ≡ suc (m + (n + p))

when rewritten with assoc m n p becomes

    suc (m + (n + p))  ≡ suc (m + (n + p))

which is proved by refl.

**Comment by GetContented** [comment]
Oh, what you're trying to say seems to be getting across. (Sorry if I'm being dense here).

Would it be correct to say `rewrite` pattern matches on the LHS of `≡` within the LHS of `=` and replaces the parts it matches with the resultant transformed pattern on the `RHS` of `≡`?

(or, at least, have I captured the gist of the understanding?)

**Comment by wadler** [comment]
I've rewritten the end of the section in question as follows. Is that clearer?

For the inductive case, we must show:

    (suc m + n) + p ≡ suc m + (n + p)

Simplifying both sides with the inductive case of addition yields the equation:

    suc ((m + n) + p) ≡ suc (m + (n + p))

This is our goal to be proved.  Rewriting by a given equation is
indicated by the keyword `rewrite` followed by a proof of that
equation.  Rewriting replaces each occurrence of the left-hand side of
the equation in the goal by the right-hand side.  In this case, after
rewriting by the inductive hypothesis our goal becomes

    suc (m + (n + p)) ≡ suc (m + (n + p))

and the proof is again given by `refl`.  Rewriting avoids
not only chains of equations but also the need to invoke `cong`.

**Comment by GetContented** [comment]
The bottom half is better than it was, definitely. 

It still wasn't clear why we were manually simplifying both sides with the inductive case of addition ourselves and how Agda does this automagically until I actually did all the steps myself, then I realised you're using the term "simplifying" here to mean what I would roughly call "specialising to the case by substitution". (In the same way that `y = 2x + 3` can be specialised into a specific case by, say, substituting `5` in for `x`, for the case where `x = 5`)

FWIW, this is the working out I did that got me to the understanding:

---

For the inductive case, we start with the rule `+-assoc′` which is `(m + n) + p ≡ m + (n + p)` as we did with the base case. We're trying to prove this proposition in the case when `m` is equal to `(suc m)`, as that's what the inductive case _is_. It's an unfortunate representation of nomenclature that we're using the same letter, `m`, to mean two different variables.

So, we sub `(suc m)` in for `m` and get `(suc m + n) + p ≡ suc m + (n + p)`, which we must prove.

Using `+-assoc′` as a rewrite replaces anything that matches the LHS (`(m + n) + p`) with the matched variables output on the RHS: `m + (n + p)`.

Because we are applying it to `(suc m + n) + p ≡ suc m + (n + p)` from above, this results in `(suc m + n) + p` being matched and replaced with `(suc m) + (n + p)` (ie subbing `(suc m)` in for `m`), which results in `(suc m) + (n + p) ≡ suc m + (n + p)`, which is trivially true by `refl`.

----

Your description is obviously so much better than mine!

**Comment by GetContented** [comment]
Both of these descriptions are ~~extremely convoluted~~ and difficult to follow, though, it seems. :(

Sorry, "extremely convoluted" is not a helpful phrase there. The intended meaning is that it's difficult to use these descriptions to pinpoint exactly which of the syntactical transformations they might refer to.

**Comment by GetContented** [comment]
> Rewriting replaces each occurrence of the left-hand side of the equation in the goal by the right-hand side. In this case, after rewriting by the inductive hypothesis our goal becomes

This sounds a little like it's replacing every literal occurrence, but my understanding is that it's replacing **matches**. Is that right? Gosh this is confusing.

For example... `m ≡ f m` replacing within `a b m ≡ m d m` should result in `(f a) (f b) (f m) ≡ m d m` not in `a b (f m) ≡ m d m` (ie variables are not literals within rewriting)

**Comment by GetContented** [comment]
It might be useful to explain some more pedestrian examples of rewrites to orient the reader on the basics of it and allow them to triangulate the semantics so that this less-than-trivial example becomes trivial?

I'll revisit this after I've had some time to let my background mind work on it.

**Comment by wadler** [comment]
I'm going to leave it as it is. If anyone wants to suggest an improved wording, please submit a pull request.

**Comment by GetContented** [comment]
Thanks! Sorry for reporting that I was having difficulties understanding. I've since realised that I should have been using the mailing list, and been learning some leanprover quite a bit and more Agda through Conor's videos, and I understand rewriting much better now. Your revised version is also much easier to understand.

**Comment by wadler** [comment]
Noted, thanks!
