### ISSUE TITLE
Release 22.08

### ISSUE THREAD

**Issue by wenkokke** [plfa/plfa.github.io#667]
In order to draft a new release, I believe we should fix all the issues tracked by the [22.07](https://github.com/plfa/plfa.github.io/milestone/1) milestone, then release the new version following [the instructions](https://plfa.github.io/Contributing/)—which will become a visible page once the milestone issues have been fixed.

**Comment by gallais** [comment]
FYI [citing](https://plfa.inf.ed.ac.uk/Citing/) currently refers to 20.08 as if it were released already but the link https://plfa.inf.ed.ac.uk/20.08/ is dead.
