### ISSUE TITLE
Fix fonts

### ISSUE THREAD

**Issue by wenkokke** [plfa/plfa.github.io#688]
![34A19A8D-61F7-4F5B-917F-FA41BA395493](https://user-images.githubusercontent.com/3983973/173830695-4ba65fe7-94a1-4646-a820-61490e565d1d.jpeg)

**Comment by fangyi-zhou** [comment]
![image](https://user-images.githubusercontent.com/7815439/174485842-4802b36c-a947-4be5-bb35-361158ee8b59.png)
Something seems wrong whenever a markdown style is used (emphasis, hyperlink, etc), the space becomes missing.

**Comment by fangyi-zhou** [comment]
> ![image](https://user-images.githubusercontent.com/7815439/174485842-4802b36c-a947-4be5-bb35-361158ee8b59.png) Something seems wrong whenever a markdown style is used (emphasis, hyperlink, etc), the space becomes missing.

Looks like that's fixed in the latest commit

**Comment by wenkokke** [comment]
> ![image](https://user-images.githubusercontent.com/7815439/174485842-4802b36c-a947-4be5-bb35-361158ee8b59.png)
> Something seems wrong whenever a markdown style is used (emphasis, hyperlink, etc), the space becomes missing.

Yeah, that's on its way to getting fixed.
