### ISSUE TITLE
Weird identifiers on website

### ISSUE THREAD

**Issue by edgardSchi** [plfa/plfa.github.io#690]
I was just reading through the [Lambda chapter](https://plfa.github.io/Lambda/) again on the website and noticed these weird identifiers in the examples:
![lambda_web](https://user-images.githubusercontent.com/32880975/173947671-36c98aa5-2f87-45cc-b186-8472765914a6.png)

The source file looks as it should:
![lambda_source](https://user-images.githubusercontent.com/32880975/173948380-f2a883bc-a9b3-4b03-9e80-fd866a6f9236.png)

I guess something went wrong while converting to HTML?

**Comment by wadler** [comment]
Thanks for the heads up, but it looks ok on my machine. Maybe it is an issue with how you have your browser configured?

**Comment by fangyi-zhou** [comment]
I think there's is something wrong with the markdown to HTML conversion, the quotes are encoded into `&quot;` and then encoded again into `&amp;quot;`, which is where it went wrong.
https://github.com/plfa/plfa.github.io/blob/9cd5af85629b6389c3b79494e066b78a8ab8b02b/Lambda/index.html#L75

**Comment by wenkokke** [comment]
@wadler This is still an issue on the live version of the book. Perhaps you were looking at a cached version.

**Comment by wenkokke** [comment]
> I think there's is something wrong with the markdown to HTML conversion, the quotes are encoded into `&quot;` and then encoded again into `&amp;quot;`, which is where it went wrong.
> 
> https://github.com/plfa/plfa.github.io/blob/9cd5af85629b6389c3b79494e066b78a8ab8b02b/Lambda/index.html#L75

That is 100% the problem, yes. I’ll have to investigate, but I think that the issue lies with the TagSoup pass [here](https://github.com/plfa/plfa.github.io/blob/dev/tools/Buildfile.hs#L274-L285) encoding HTML entities in the Markdown source.

**Comment by wenkokke** [comment]
Fixed in 1879b03ac93224fc8a58adfa6babf8240dc03e94
