### ISSUE TITLE
"Getting Started" failure to build and install `agda` due to geniplate-mirror maybe?

### ISSUE THREAD

**Issue by anadon** [plfa/plfa.github.io#692]
Hello all, tech stack looked interesting so I figured I'd try and play around.

Following the "Getting Started" section for Linux, the build/install step using `stack` has been failing.  The error at the bottom I kept getting is `<stderr>: commitAndReleaseBuffer: invalid argument (invalid character)`.  I'm re-running the same `stack` install command and each time I do, I received different output with the appearance of progress between runs until the only dependency being built was `geniplate-mirror`.  The following should be able to reproduce the error.  

```
sh <(curl -L https://nixos.org/nix/install) --no-daemon
nix-env -iA git stack
git clone https://github.com/agda/agda.git
cd agda
git checkout v2.6.1.3
for i in {1..20}
do
stack install --system-ghc --stack-yaml stack-8.2.2.yaml
done
```

**Comment by anadon** [comment]
Looking over the CI, there actually isn't any testing that listed instructions in the "Getting Started" work.  That might be some low-hanging fruit to fix.

**Comment by wenkokke** [comment]
I don’t think we currently recommend using stock for anything? Are you using the latest version of the instructions in “getting started“?

**Comment by wenkokke** [comment]
Ignore the linked commit. It’s attempting to fix 690, not this issue.

**Comment by wenkokke** [comment]
Closing as the current documentation does not mention Stack.

**Comment by anadon** [comment]
Since the page changed over night, I'm still having the same category of issue.

```
anadon@Poymon:~/Documents/code/agda$ cabal install Agda-2.6.2.2
cabal: sdist of Agda-2.6.1.3: filepath wildcard 'doc/user-manual.pdf' does not
match any files.
```

**Comment by anadon** [comment]
@wenkokke It looks like https://github.com/anko/txm could help here.  Don't let the emphasis on JavaScript scare you away, the docs claim it is suitable for any language.

**Comment by wenkokke** [comment]
@anadon This seems like it’s an Agda issue. However, are you calling…
```bash
cabal install Agda-2.6.2.2
```
…from any particular directory? Because that error feels like you’re calling it from within a copy of the Agda repository—it’s complaining that you didn’t run the part of the Agda build process that generates the docs—but cloning the repository is no longer part of the instructions. Please rerun the command from any other directory.

**Comment by wenkokke** [comment]
> @wenkokke It looks like https://github.com/anko/txm could help here. Don't let the emphasis on JavaScript scare you away, the docs claim it is suitable for any language.

That’s very cool! I’ll definitely keep that in mind. However, installing Agda should be a single command—assuming you’ve already got GHC and Cabal—so that won’t help here.

**Comment by anadon** [comment]
> ```shell
> cabal
> ```

It was from in an instance of the agda git repo.  I just picked up in my shell where I last left off.  When running from my home directory, it works as described.

As for the installation step in getting started, that isn't why that repo is interesting.  What that repo does is add CI so all the shell commands and code snippets are valid and working as intended.  This is an area in need of improvement.  Having versions of instructions that break deters potential users.  I'll give it a few tries, but for me this is number 4 to get anything actually working and I'll drop it myself soon.  If I can't get it with multiple tries, how can I actually suggest it and have that mean anything to anyone I suggest it to?  Having code snippets always work is an important level of QA which should be adopted.
