### ISSUE TITLE
README is incorrect

### ISSUE THREAD

**Issue by peterb12** [plfa/plfa.github.io#701]
The README contains the line:

> Open the `nats.agda` file you created earlier, and load and type-check the file by typing [`C-c C-l`][agda-docs-emacs-notation].

But the file "nats.agda" is not referenced anywhere else in the README.

**Comment by wenkokke** [comment]
Ohh, we removed that ‘cuz it’s in the Agda installation guide now, but didn’t catch this reference! Thanks!
