### ISSUE TITLE
Can't `make build` on MacOS 

### ISSUE THREAD

**Issue by peterb12** [plfa/plfa.github.io#702]
Attempting to follow the instructions at https://plfa.github.io/GettingStarted/ step by step from a machine with no previous Agda install, after cloning plfa from GitHub and typing "make build", I get:

```
% make build
Building PLFA...
Up to date
Using Agda standard library version v1.3
# sass (for _site/assets/css/highlight.css)
Error when running Shake build system:
  at want, called at src/Development/Shake/Internal/Args.hs:83:67 in shk-0.19.6-b8d011e5:Development.Shake.Internal.Args
* Depends on: build
  at need, called at tools/Buildfile.hs:236:9 in main:Main
* Depends on: _site/assets/css/highlight.css
* Raised the exception:
npm: createProcess: exec: invalid argument (Bad file descriptor)
```

Happy to provide logs or other info if that helps.

**Comment by wenkokke** [comment]
The instructions for compiling the entire book locally aren’t there yet, but you won’t need those to read the book or do the exercises.

The specific error you’re running into is that you don’t have node installed.

**Comment by wenkokke** [comment]
> Attempting to follow the instructions at https://plfa.github.io/GettingStarted/ step by step from a machine with no previous Agda install, after cloning plfa from GitHub and typing "make build", I get:
> 
> ```
> % make build
> Building PLFA...
> Up to date
> Using Agda standard library version v1.3
> # sass (for _site/assets/css/highlight.css)
> Error when running Shake build system:
>   at want, called at src/Development/Shake/Internal/Args.hs:83:67 in shk-0.19.6-b8d011e5:Development.Shake.Internal.Args
> * Depends on: build
>   at need, called at tools/Buildfile.hs:236:9 in main:Main
> * Depends on: _site/assets/css/highlight.css
> * Raised the exception:
> npm: createProcess: exec: invalid argument (Bad file descriptor)
> ```
> 
> Happy to provide logs or other info if that helps.

I think that nowhere in the instructions it says to run “make build”, am I right?

**Comment by peterb12** [comment]
> I think that nowhere in the instructions it says to run “make build”, am I right?

That's accurate. This is related to the README question in issue #701 in that my thought process was something like "well....maybe `nat.agda` is created if I build the `plfa` project". Good to know it's not necessary.
