### ISSUE TITLE
README refers to nats.agda rather than src/plfa/part1/Naturals.lagda.md

### ISSUE THREAD

**Issue by anadon** [plfa/plfa.github.io#715]
https://plfa.github.io/GettingStarted/#check-if-agda-mode-was-installed-correctly refers to a file named `nats.agda`, but no such file has been referenced up to this point.  In fact, this is the only reference to such a file in the whole repo in the dev branch; https://github.com/plfa/plfa.github.io/search?q=nats.agda .

**Comment by anadon** [comment]
It looks like there's an indirect reference to the same file later on.  'load and type-check the file'

**Comment by wenkokke** [comment]
Yes, I believe @wadler fixed this at some point, but didn’t push the changes.

It references a removed instructions—now that [the linked Agda installation instructions](https://github.com/plfa/plfa.github.io#install-agda) have some instructions for testing if everything works as expected.
 
It should be changed to any PLFA chapter, e.g., `src/plfa/part1/Naturals.lagda.md`.
