### ISSUE TITLE
PDF link broken

### ISSUE THREAD

**Issue by anadon** [plfa/plfa.github.io#719]
The PDF version of the book is no longer at https://plfa.github.io/plfa.pdf .  When searching on Google for the PDF and Epub versions, one comes across https://mobile.twitter.com/wenkokke/status/1430898902731943936 and https://plfa.github.io/Announcements/ .  It looks like there's maybe supposed to be a strike through in the announcement for the PDF?

**Comment by wenkokke** [comment]
Could you check for me if your reader supports EPUB3?

**Comment by wenkokke** [comment]
I'll add another compression step to the build, which might help, but will make the build less portable.

If you want to test it locally, you can install Calibre and run `ebook-polish` with approppriate flags. The subfonting is especially beneficial.

**Comment by wenkokke** [comment]
That's meant to be a strike through, thanks. Might've turned off that Markdown extension by accident. 

PDF compilation is no longer supported, though all the components are still there and ready to be put together if you're interested.

**Comment by anadon** [comment]
I need to crawl before I walk here, so I'm not going to take that one up.  My TODO list already spans years.
