### ISSUE TITLE
"Technical results" in Bisimulation

### ISSUE THREAD

**Issue by fangyi-zhou** [plfa/plfa.github.io#732]
In Bisimulation Chapter, the phrase "technical result" is used to describe the lemmas that simulation commutes with value, renaming, and substitution.

Based on how the "techncial results" are introduced, namely: 
> We need a number of technical results.

May I suggest to change that phrase to something like "mechanical lemmas" or "mechanical results"? 
Alternatively, any clarification on how this phrase is intended to mean is helpful for me to translate this chapter.

Many thanks in advance

**Comment by wadler** [comment]
"Technical result" is a standard phrase in the literature, and I think it is the correct one to use.

Typically, one uses this phrase for a result that is important, and possibly difficult, but uninteresting. "As a technical result, we require a substitution lemma".

I don't think "mechanical lemma" or "mechanical result" is commonly used, but "technical result" is.

**Comment by fangyi-zhou** [comment]
Thanks for the clarification, I wasn't aware that "technical result" is a standard phrase.
