### ISSUE TITLE
ghcup set does not work on a fresh installation

### ISSUE THREAD

**Issue by hackedy** [plfa/plfa.github.io#762]
Hi, the build directions for ghcup use
```
ghcup set ghc 9.2
ghcup set cabal recommended
```
I didn't have ghc or cabal installed to begin with, so I had to actually write
```
ghcup install ghc 9.2.4
ghcup install cabal recommended
ghcup set ghc 9.2.4
ghcup set cabal recommended
```

**Comment by hackedy** [comment]
If you try to `set` something with the TUI it prompts you to install it, so maybe the fix is to only have a reference to the TUI?

**Comment by wenkokke** [comment]
Ah, we tested these with the TUI, and assumed. 

Did `ghcup install ghc 9.2` work? I see you also switched to full version numbers.

**Comment by hackedy** [comment]
`ghcup install ghc 9.2` works, it prints a message saying "assuming you meant 9.2.4," but if I try it with set I have to spell it out. Otherwise:
```
% ghcup set ghc 9.2
[ Error ] The version 9.2 of the tool ghc is not installed.
% ghcup set ghc 9.2.4
# ... succeeds ...
```

Thank you for writing PLFA, I'm really enjoying it so far :)
