### ISSUE TITLE
`_^_` not imported in `Induction.lagda.md`

### ISSUE THREAD

**Issue by ShaolunWang** [plfa/plfa.github.io#766]
As title stated, in `Induction.lagda.md` we only have`open import Data.Nat using (ℕ; zero; suc; _+_; _*_; _∸_)`. However `Exercise +*^ (stretch)` requires to use `^`. The operator was imported in the previous chapter (Naturals), but not here.

**Comment by wenkokke** [comment]
@ShaolunWang I'd happily accept a PR which addresses this.

**Comment by wadler** [comment]
@ShaolunWang Indeed. Please write a pull request, and we will accept. Then your name automatically goes into the acknowledgements.
