### ISSUE TITLE
Use citations instead of manual references

### ISSUE THREAD

**Issue by wenkokke** [plfa/plfa.github.io#806]
The chapters on denotational semantics use manually kept lists of references, rather than the builtin citation mechanism.

@jsiek Would you be happy to change this? I can help with the technical details. Specifically, we should create add the referenced works to the bibTeX file and use [citations](https://pandoc.org/MANUAL.html#org-citations).

**Comment by jsiek** [comment]
Will do after the holidays!

**Comment by wenkokke** [comment]
See [_How to add a citation_](https://plfa.github.io/Contributing/#how-to-add-a-citation) for details on how to use citations! :)

**Comment by jsiek** [comment]
What branch should I commit this change to?

**Comment by jsiek** [comment]
Ok, looks like these days I should do a pull request from a new branch. Will do!

**Comment by jsiek** [comment]
PR #810 is in progress to resolve this issue.

**Comment by wenkokke** [comment]
Closed by #810
