### ISSUE TITLE
Type signatures vs. proof variables

### ISSUE THREAD

**Issue by buggymcbugfix** [plfa/plfa.github.io#81]
Take
```agda
+-identity′ : ∀ (n : ℕ) → n + zero ≡ n
-- for any Natural number n, prove that n + zero equals n
+-identity′ zero = refl
-- when n is 0...
+-identity′ (suc n) rewrite +-identity′ n = refl
-- when n is the successor of some n !?
```
Here the comments narrate what goes on the head of the complete ℕ00𝔹 that I am.

Wouldn't it be less confusing to pattern match on something that is not called `n` in the second clause? E.g.:

```agda
+-identity′ (suc n′) rewrite +-identity′ n′ = refl
-- when n is the successor of some n′ ...
```

**Comment by wadler** [comment]
This is a matter of style. Some would indeed prefer to do it in the style you recommend.

**Comment by buggymcbugfix** [comment]
Would it be worth making a note of this in the book? If yes, I'd be happy to open a PR.
