### ISSUE TITLE
Nonsensical exercise?

### ISSUE THREAD

**Issue by buggymcbugfix** [plfa/plfa.github.io#82]
There seems to be a conflict between the given definitions and the immediately following exercise:

> - Preorder Any relation that is reflexive and transitive.
> - Partial order Any preorder that is also anti-symmetric.

vs

> # Exercise `orderings`
>
> Give an example of a preorder that is not a partial order.
>
> Give an example of a partial order that is not a preorder. _[Not possible according to definitions.]_

**Comment by wadler** [comment]
Thanks. Fixed. In the second sentence, replaced "preorder" by "total order".
