### ISSUE TITLE
Chapter on Relations suggests that it is the first time it's using the `where` clause, but it has been used before.

### ISSUE THREAD

**Issue by Ei30metry** [plfa/plfa.github.io#830]
In part 1, Relations, after introducing the `with` clause inside ≤-total, the book shows the same proof [ ≤-total′ ](https://plfa.github.io/Relations/?dark=true#plfa_plfa-part1-Relations-15289) written with `where` clause; Then it says that it's the first time that we are using a `where` clause and explains it. When in fact,  in the second chapter, [+-assoc-2](https://plfa.github.io/Induction/?dark=true#plfa_plfa-part1-Induction-11113) it had already been used twice.

**Comment by wenkokke** [comment]
The easiest fix is perhaps to simply remove the where clauses in `+-assoc`. Each of those definitions can easily stand alone as a top-level definition, building up from `+-assoc-0`.
