### ISSUE TITLE
Update Agda to 2.6.3 to Prevent Emacs "agda-mode compile" Error

### ISSUE THREAD

**Issue by benbellick** [plfa/plfa.github.io#832]
https://github.com/plfa/plfa.github.io/blob/51c71b2ad10fa7b0d921bb11fd3a5553588f012c/README.md?plain=1#L66

The readme instructs new users to install Agda 2.6.2.2. Following along the instructions as written, I received the following compile error:
```
 ~ % agda-mode compile
Loading quail/latin-ltx...

In toplevel form:
.cabal/store/ghc-9.2.4/Agd-2.6.2.2-e8b2c246/share/emacs-mode/agda2-mode.el:1308:2: Error:  docstring wider than 80 characters
Unable to compile the following Emacs Lisp files:
  ~/.cabal/store/ghc-9.2.4/Agd-2.6.2.2-e8b2c246/share/emacs-mode/agda2-mode.el
```
I am running GNU Emacs 28.2 on Mac OS Ventura 13.1. 

One of the changes made in Agda 2.6.3 is to reduce the docstrings to be shorter than 80 characters, [as seen in this commit](https://github.com/agda/agda/commit/5762fccc1b5ffa7c24e35b53c368ebb7c9d827ec). Running `agda-mode compile` succeeds with version Agda 2.6.3. 

My suggestion is to recommend users install Agda 2.6.3 rather than 2.6.2.2. Will this cause any foreseeable issues? Thanks!

**Comment by wenkokke** [comment]
No, PLFA compiles with 2.6.3 just fine. If you're happy to submit a pull request updating the version, I'd be happy to merge it. Otherwise, I'll get to that eventually.

**Comment by wenkokke** [comment]
See: https://github.com/plfa/plfa.github.io/actions/runs/4227084954/jobs/7341200625

**Comment by benbellick** [comment]
#833
