### ISSUE TITLE
plfa.epub cannot be uploaded to Android/Google Play Books

### ISSUE THREAD

**Issue by dimpase** [plfa/plfa.github.io#837]
attempts to upload https://plfa.github.io/plfa.epub to Google's Play Books (i.e. to play.google.com/books)  end up in an error "Upload failed".

(Broken in browser, and on an Android device - although it's most probably the same error)

**Comment by wenkokke** [comment]
I'd need more information to find out what's going on.

In general, creating ebooks that work in multiple different places is a nightmare, and we don't have the capacity to do so.

If you find a workaround for this (possibly  Google Books specific) glitch, please let me know.

**Comment by dimpase** [comment]
To reproduce this one, all you need is a Google account. I only noticed as I want to read the book offline...

**Comment by wenkokke** [comment]
Are you able to provide more information? Perhaps an error message?

**Comment by dimpase** [comment]
On Mon, 27 Feb 2023, 15:48 Wen Kokke, ***@***.***> wrote:

> Are you able to provide more information? Perhaps an error message?
>

it is very short and uniformative.

 "Upload failed Click here for more info".

And after clicking there: "your file might be corrupt or not compatible".

I'd rule out "corrupt" on my machines - I tried few times on 2 devices.

**Comment by wenkokke** [comment]
Closing this since there is not enough information, and no bandwidth to investigate EPUB incompatibilities.
