### ISSUE TITLE
Strange artefact when clicking the light/dark mode icon

### ISSUE THREAD

**Issue by wenkokke** [plfa/plfa.github.io#839]
After clicking the light/dark mode icon, the replacement appears followed by *what appears to be* an underscore:
![Screenshot 2023-02-27 at 16 58 01](https://user-images.githubusercontent.com/3983973/221629200-9e05dd67-cda5-47ac-9c5d-9b1dd9a9a68c.png)
However, the underscore disappears when opening the developer tools, which makes it difficult to diagnose what is *actually* going on.

@cyberglot: Could you have a look?

**Comment by cyberglot** [comment]
Your code has decorations for `a`:

```
a:hover {
  color: #bbb;
  text-decoration: underline;
}
```

You need to remove it for `a i`s (or in CSS parlance, add a `text-decoration: none`).
