### ISSUE TITLE
Unrecognized option: --cubical-compatible

### ISSUE THREAD

**Issue by freeman42x** [plfa/plfa.github.io#991]
When running via precompiled version of Agda 2.6.0.1 for Windows type-checking errors with:

```
\plfa\src\plfa\part1\Naturals.lagda.md:263,8-51
Unrecognized option: --cubical-compatible
when scope checking the declaration
  import Relation.Binary.PropositionalEquality as Eq
```

The solution was to install agda via cabal: `cabal install Agda-2.6.3`

The fact that Agda 2.6.3 is required should be probably clearly documented in the readme.

Hope this helps anyone else running in to the error.

**Comment by wenkokke** [comment]
Closing, as the fact that Agda 2.6.3 is required is documented in the README.
