### ISSUE TITLE
`foldr-++` (Lists): the postulated form is misleading and causing type mismatch

### ISSUE THREAD

**Issue by adql** [plfa/plfa.github.io#997]
In [exercise `foldr-++`](https://github.com/plfa/plfa.github.io/blob/e52c39bc31abf7dd4a6731ff607ad52f9e9f0f64/src/plfa/part1/Lists.lagda.md?plain=1#L648) the student is asked to show that

``` agda
foldr _⊗_ e (xs ++ ys) ≡ foldr _⊗_ (foldr _⊗_ e ys) xs
```

[Later in the chapter](https://github.com/plfa/plfa.github.io/blob/e52c39bc31abf7dd4a6731ff607ad52f9e9f0f64/src/plfa/part1/Lists.lagda.md?plain=1#L802), in section "Monoids", this is postulated as specialized to a monoidal action:

``` agda
postulate
  foldr-++ : ∀ {A : Set} (_⊗_ : A → A → A) (e : A) (xs ys : List A) →
    foldr _⊗_ e (xs ++ ys) ≡ foldr _⊗_ (foldr _⊗_ e ys) xs
```

Notice especially the types of `_⊗_ ` and `e`.

Since this has to be commented out in order to solve the exercise above, the student might adopt the type signature to be used in their own solution. This is not a problem for solving that exercise – however, the [next exercise](https://github.com/plfa/plfa.github.io/blob/e52c39bc31abf7dd4a6731ff607ad52f9e9f0f64/src/plfa/part1/Lists.lagda.md?plain=1#L658) `foldr-∷` asks:

> Show as a consequence of `foldr-++` above that
>
>    xs ++ ys ≡ foldr _∷_ ys xs

This doesn't work with the postulated type signature since `_∷_ : A → List A → List A` and `[] : List A` , whereas `foldr-++` is postulated with `_⊗_ : A → A → A` and `e : A`. This misleads the student to unnecessary frustration.

I suggest postulating `foldr-++` in the exercise's subsection itself (as usually done throughout the book) with `∀ {A B : Set} (_⊗_ : A → B → B) (e : B) ...`.

**Comment by wadler** [comment]
Thank you for your thoughtful suggestion.

I'd be delighted to accept a pull request along the lines you suggest.
